package container

import (
	"archive/tar"
	"bufio"
	"bytes"
	"context"
	"fmt"
	"log/slog"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	dockercontainer "github.com/docker/docker/api/types/container"
	"github.com/docker/docker/client"

	"github.com/daytonaio/daytona/libs/netleash/pkg/runtime"
)

// Docker implements runtime.Runtime using the Docker Engine API.
type Docker struct {
	docker *client.Client
}

var _ runtime.Runtime = (*Docker)(nil)

// NewDocker creates a Docker runtime client from environment configuration.
func NewDocker() (*Docker, error) {
	dc, err := client.NewClientWithOpts(client.FromEnv, client.WithAPIVersionNegotiation())
	if err != nil {
		return nil, fmt.Errorf("docker client: %w", err)
	}
	return &Docker{docker: dc}, nil
}

// ResolveCgroup gets the cgroup v2 path for a Docker container.
func (d *Docker) ResolveCgroup(ctx context.Context, id string) (string, error) {
	info, err := d.docker.ContainerInspect(ctx, id)
	if err != nil {
		return "", fmt.Errorf("docker inspect: %w", err)
	}

	pid := info.State.Pid
	if pid == 0 {
		return "", fmt.Errorf("container %s is not running", id)
	}

	// Read the process's cgroup v2 path from /proc/<pid>/cgroup.
	cgroupFile := filepath.Join("/proc", strconv.Itoa(pid), "cgroup")
	f, err := os.Open(cgroupFile)
	if err != nil {
		return "", fmt.Errorf("reading %s: %w", cgroupFile, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		// cgroup v2 line format: "0::<path>"
		parts := strings.SplitN(line, ":", 3)
		if len(parts) == 3 && parts[0] == "0" && parts[1] == "" {
			cgPath := filepath.Join("/sys/fs/cgroup", parts[2])
			if stat, err := os.Stat(cgPath); err == nil && stat.IsDir() {
				return cgPath, nil
			}
			return "", fmt.Errorf("cgroup path does not exist: %s", cgPath)
		}
	}

	return "", fmt.Errorf("no cgroup v2 entry found in %s", cgroupFile)
}

// GetIP returns the container's own IP address on its Docker network.
func (d *Docker) GetIP(ctx context.Context, id string) (string, error) {
	info, err := d.docker.ContainerInspect(ctx, id)
	if err != nil {
		return "", fmt.Errorf("docker inspect: %w", err)
	}

	for _, nw := range info.NetworkSettings.Networks {
		if nw.IPAddress != "" {
			return nw.IPAddress, nil
		}
	}
	return "", fmt.Errorf("container %s has no IP (host network mode?)", id)
}

// GetGateway returns the gateway IP the container uses to reach the host.
func (d *Docker) GetGateway(ctx context.Context, id string) (string, error) {
	info, err := d.docker.ContainerInspect(ctx, id)
	if err != nil {
		return "", fmt.Errorf("docker inspect: %w", err)
	}

	for _, nw := range info.NetworkSettings.Networks {
		if nw.Gateway != "" {
			return nw.Gateway, nil
		}
	}
	// Host network mode — proxy is reachable on localhost.
	return "127.0.0.1", nil
}

// InjectEnv copies an env file and CA cert into the container.
// The user must run `source /tmp/.netleash-env` inside the container to activate.
func (d *Docker) InjectEnv(ctx context.Context, id string, cfg runtime.EnvConfig) error {
	gatewayIP, err := d.GetGateway(ctx, id)
	if err != nil {
		return fmt.Errorf("getting container gateway: %w", err)
	}

	_, port, err := net.SplitHostPort(cfg.ProxyAddr)
	if err != nil {
		return fmt.Errorf("parsing proxy address: %w", err)
	}
	proxyURL := fmt.Sprintf("http://%s:%s", gatewayIP, port)

	// Copy CA certs into the container first (needed before keytool).
	haveTrustStore := false
	if cfg.CACertFile != "" {
		if err := d.copyFileToContainer(ctx, id, cfg.CACertFile, "/tmp/.netleash-ca.pem"); err != nil {
			return fmt.Errorf("copying CA cert: %w", err)
		}
		if err := d.copyFileToContainer(ctx, id, cfg.RawCACert, "/tmp/.netleash-ca-raw.pem"); err != nil {
			return fmt.Errorf("copying raw CA cert: %w", err)
		}

		// Try to create a JVM truststore inside the container (best effort).
		err := d.execInContainer(ctx, id, []string{"sh", "-c",
			`command -v keytool >/dev/null 2>&1 || exit 1; ` +
				`CACERTS=""; ` +
				`[ -n "$JAVA_HOME" ] && [ -f "$JAVA_HOME/lib/security/cacerts" ] && CACERTS="$JAVA_HOME/lib/security/cacerts"; ` +
				`[ -z "$CACERTS" ] && [ -f /etc/ssl/certs/java/cacerts ] && CACERTS=/etc/ssl/certs/java/cacerts; ` +
				`[ -z "$CACERTS" ] && CACERTS=$(find /usr -name cacerts -path '*/security/*' 2>/dev/null | head -1); ` +
				`[ -z "$CACERTS" ] && exit 1; ` +
				`cp "$CACERTS" /tmp/.netleash-truststore.p12 && ` +
				`keytool -importcert -noprompt -alias netleash-ca -file /tmp/.netleash-ca-raw.pem ` +
				`-keystore /tmp/.netleash-truststore.p12 -storepass changeit >/dev/null 2>&1`,
		})
		haveTrustStore = err == nil
	}

	// Build env file content (plain key=value exports, no shell logic).
	var sb strings.Builder
	sb.WriteString("# Generated by netleash — source this to activate secret injection\n")
	for _, s := range cfg.Secrets {
		fmt.Fprintf(&sb, "export %s='%s'\n", s.Name, s.Placeholder)
	}
	fmt.Fprintf(&sb, "export HTTP_PROXY='%s'\n", proxyURL)
	fmt.Fprintf(&sb, "export HTTPS_PROXY='%s'\n", proxyURL)
	fmt.Fprintf(&sb, "export http_proxy='%s'\n", proxyURL)
	fmt.Fprintf(&sb, "export https_proxy='%s'\n", proxyURL)

	// JVM ignores *_PROXY env vars; it reads proxy settings from system properties.
	javaOpts := fmt.Sprintf("-Dhttp.proxyHost=%s -Dhttp.proxyPort=%s -Dhttps.proxyHost=%s -Dhttps.proxyPort=%s", gatewayIP, port, gatewayIP, port)
	if haveTrustStore {
		javaOpts += " -Djavax.net.ssl.trustStore=/tmp/.netleash-truststore.p12 -Djavax.net.ssl.trustStorePassword=changeit"
	}
	fmt.Fprintf(&sb, "export JAVA_TOOL_OPTIONS='%s'\n", javaOpts)

	if cfg.CACertFile != "" {
		const containerCAPath = "/tmp/.netleash-ca.pem"
		fmt.Fprintf(&sb, "export SSL_CERT_FILE='%s'\n", containerCAPath)
		fmt.Fprintf(&sb, "export NODE_EXTRA_CA_CERTS='%s'\n", containerCAPath)
		fmt.Fprintf(&sb, "export REQUESTS_CA_BUNDLE='%s'\n", containerCAPath)
		fmt.Fprintf(&sb, "export CURL_CA_BUNDLE='%s'\n", containerCAPath)
	}

	// Copy env file content directly into the container (no temp file needed).
	if err := d.copyBytesToContainer(ctx, id, []byte(sb.String()), "/tmp/.netleash-env"); err != nil {
		return fmt.Errorf("copying env file: %w", err)
	}

	slog.Info("env injected into container — run: source /tmp/.netleash-env", "container", id)
	return nil
}

// CleanupEnv removes injected files from the container (best effort).
func (d *Docker) CleanupEnv(ctx context.Context, id string) {
	d.execInContainer(ctx, id, []string{"rm", "-f",
		"/tmp/.netleash-env", "/tmp/.netleash-ca.pem", "/tmp/.netleash-ca-raw.pem", "/tmp/.netleash-truststore.p12"})
	slog.Debug("cleaned up injected files from container", "container", id)
}

// Close releases the Docker client resources.
func (d *Docker) Close() error {
	return d.docker.Close()
}

// copyFileToContainer reads a local file and copies it into the container at dstPath.
func (d *Docker) copyFileToContainer(ctx context.Context, containerID, srcPath, dstPath string) error {
	data, err := os.ReadFile(srcPath)
	if err != nil {
		return fmt.Errorf("reading %s: %w", srcPath, err)
	}
	return d.copyBytesToContainer(ctx, containerID, data, dstPath)
}

// copyBytesToContainer writes raw bytes into a file inside the container at dstPath.
func (d *Docker) copyBytesToContainer(ctx context.Context, containerID string, data []byte, dstPath string) error {
	dir := filepath.Dir(dstPath)
	name := filepath.Base(dstPath)

	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)
	if err := tw.WriteHeader(&tar.Header{
		Name: name,
		Mode: 0644,
		Size: int64(len(data)),
	}); err != nil {
		return err
	}
	if _, err := tw.Write(data); err != nil {
		return err
	}
	tw.Close()

	return d.docker.CopyToContainer(ctx, containerID, dir, &buf, dockercontainer.CopyToContainerOptions{})
}

// execInContainer runs a command inside the container and returns an error if it fails.
func (d *Docker) execInContainer(ctx context.Context, containerID string, cmd []string) error {
	resp, err := d.docker.ContainerExecCreate(ctx, containerID, dockercontainer.ExecOptions{
		Cmd:          cmd,
		AttachStdout: true,
		AttachStderr: true,
	})
	if err != nil {
		return fmt.Errorf("exec create: %w", err)
	}

	if err := d.docker.ContainerExecStart(ctx, resp.ID, dockercontainer.ExecStartOptions{}); err != nil {
		return fmt.Errorf("exec start: %w", err)
	}

	// Check exit code.
	inspect, err := d.docker.ContainerExecInspect(ctx, resp.ID)
	if err != nil {
		return fmt.Errorf("exec inspect: %w", err)
	}
	if inspect.ExitCode != 0 {
		return fmt.Errorf("exec exited with code %d", inspect.ExitCode)
	}
	return nil
}
