export const AUDIT_STORAGE_ADAPTER = 'AUDIT_STORAGE_ADAPTER'
export const AUDIT_LOG_PUBLISHER = 'AUDIT_LOG_PUBLISHER'
export const AUDIT_KAFKA_SERVICE = 'AUDIT_KAFKA_SERVICE'
export const AUDIT_KAFKA_TOPIC = 'audit-logs'
