{{- if and .Values.minio.enabled .Values.minio.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ include "preview.namespace" . }}
  name: {{ include "preview.fullname" . }}-minio-data
  labels:
    {{- include "preview.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.minio.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.minio.persistence.size | quote }}
{{- end }}
