{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "preview.namespace" . }}
  name: {{ include "preview.fullname" . }}-minio
  labels:
    {{- include "preview.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.minio.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "preview.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: minio
{{- end }}
