{{- if .Values.registry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "preview.namespace" . }}
  name: {{ include "preview.fullname" . }}-registry
  labels:
    {{- include "preview.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "preview.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: registry
  template:
    metadata:
      labels:
        {{- include "preview.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: registry
    spec:
      containers:
        - name: registry
          image: "{{ .Values.registry.image.repository }}:{{ .Values.registry.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /var/lib/registry
          readinessProbe:
            httpGet:
              path: /v2/
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            {{- toYaml .Values.registry.resources | nindent 12 }}
      volumes:
        - name: data
          emptyDir: {}
{{- end }}
