{{- if and .Values.registry.enabled .Values.registry.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ include "preview.namespace" . }}
  name: {{ include "preview.fullname" . }}-registry-data
  labels:
    {{- include "preview.labels" . | nindent 4 }}
    app.kubernetes.io/component: registry
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.registry.persistence.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.registry.persistence.size | quote }}
{{- end }}
