// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package firewall

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type firewallLsmExecPathKey struct {
	_    structs.HostLayout
	Path [256]int8
}

// loadFirewallLsm returns the embedded CollectionSpec for firewallLsm.
func loadFirewallLsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_FirewallLsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load firewallLsm: %w", err)
	}

	return spec, err
}

// loadFirewallLsmObjects loads firewallLsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*firewallLsmObjects
//	*firewallLsmPrograms
//	*firewallLsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadFirewallLsmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadFirewallLsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// firewallLsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallLsmSpecs struct {
	firewallLsmProgramSpecs
	firewallLsmMapSpecs
	firewallLsmVariableSpecs
}

// firewallLsmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallLsmProgramSpecs struct {
	ExecFilter *ebpf.ProgramSpec `ebpf:"exec_filter"`
}

// firewallLsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallLsmMapSpecs struct {
	AllowedExecs   *ebpf.MapSpec `ebpf:"allowed_execs"`
	ExecEvents     *ebpf.MapSpec `ebpf:"exec_events"`
	TargetCgroupId *ebpf.MapSpec `ebpf:"target_cgroup_id"`
}

// firewallLsmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type firewallLsmVariableSpecs struct {
}

// firewallLsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadFirewallLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallLsmObjects struct {
	firewallLsmPrograms
	firewallLsmMaps
	firewallLsmVariables
}

func (o *firewallLsmObjects) Close() error {
	return _FirewallLsmClose(
		&o.firewallLsmPrograms,
		&o.firewallLsmMaps,
	)
}

// firewallLsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadFirewallLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallLsmMaps struct {
	AllowedExecs   *ebpf.Map `ebpf:"allowed_execs"`
	ExecEvents     *ebpf.Map `ebpf:"exec_events"`
	TargetCgroupId *ebpf.Map `ebpf:"target_cgroup_id"`
}

func (m *firewallLsmMaps) Close() error {
	return _FirewallLsmClose(
		m.AllowedExecs,
		m.ExecEvents,
		m.TargetCgroupId,
	)
}

// firewallLsmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadFirewallLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallLsmVariables struct {
}

// firewallLsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadFirewallLsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type firewallLsmPrograms struct {
	ExecFilter *ebpf.Program `ebpf:"exec_filter"`
}

func (p *firewallLsmPrograms) Close() error {
	return _FirewallLsmClose(
		p.ExecFilter,
	)
}

func _FirewallLsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed firewalllsm_bpfeb.o
var _FirewallLsmBytes []byte
