/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddToWarmPoolResponseDto
 */
export interface AddToWarmPoolResponseDto {
  /**
   * Whether the operation was successful
   * @type {boolean}
   * @memberof AddToWarmPoolResponseDto
   */
  success: boolean
  /**
   * ID of the created warm pool entry
   * @type {string}
   * @memberof AddToWarmPoolResponseDto
   */
  warmPoolId?: string
  /**
   * ID of the copied snapshot
   * @type {string}
   * @memberof AddToWarmPoolResponseDto
   */
  copiedSnapshotId?: string
  /**
   * Error message if operation failed
   * @type {string}
   * @memberof AddToWarmPoolResponseDto
   */
  error?: string
}
