/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddCollaboratorDto
 */
export interface AddCollaboratorDto {
  /**
   * User ID to add as collaborator
   * @type {string}
   * @memberof AddCollaboratorDto
   */
  userId: string
  /**
   * Access mode
   * @type {string}
   * @memberof AddCollaboratorDto
   */
  mode: AddCollaboratorDtoModeEnum
}

export const AddCollaboratorDtoModeEnum = {
  READ: 'read',
  WRITE: 'write',
} as const

export type AddCollaboratorDtoModeEnum = (typeof AddCollaboratorDtoModeEnum)[keyof typeof AddCollaboratorDtoModeEnum]
