/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AddToWarmPoolDto
 */
export interface AddToWarmPoolDto {
  /**
   * Pool number
   * @type {number}
   * @memberof AddToWarmPoolDto
   */
  pool: number
  /**
   * Target region
   * @type {string}
   * @memberof AddToWarmPoolDto
   */
  target: AddToWarmPoolDtoTargetEnum
}

export const AddToWarmPoolDtoTargetEnum = {
  US: 'us',
  EU: 'eu',
} as const

export type AddToWarmPoolDtoTargetEnum = (typeof AddToWarmPoolDtoTargetEnum)[keyof typeof AddToWarmPoolDtoTargetEnum]
