/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuditLogFiltersDto
 */
export interface AuditLogFiltersDto {
  /**
   * Filter by actor email
   * @type {string}
   * @memberof AuditLogFiltersDto
   */
  actorEmail?: string
  /**
   * Filter by action type
   * @type {string}
   * @memberof AuditLogFiltersDto
   */
  action?: string
  /**
   * Filter by target type
   * @type {string}
   * @memberof AuditLogFiltersDto
   */
  targetType?: string
  /**
   * Filter by target ID
   * @type {string}
   * @memberof AuditLogFiltersDto
   */
  targetId?: string
  /**
   * Filter by start date
   * @type {Date}
   * @memberof AuditLogFiltersDto
   */
  startDate?: Date
  /**
   * Filter by end date
   * @type {Date}
   * @memberof AuditLogFiltersDto
   */
  endDate?: Date
}
