/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { AuditLogResponseDto } from './audit-log-response-dto'

/**
 *
 * @export
 * @interface AuditLogSearchDataDto
 */
export interface AuditLogSearchDataDto {
  /**
   * List of audit logs
   * @type {Array<AuditLogResponseDto>}
   * @memberof AuditLogSearchDataDto
   */
  logs: Array<AuditLogResponseDto>
}
