/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AuditLogResponseDto {
    /**
     * Audit log ID
     */
    'id': string;
    /**
     * Actor ID
     */
    'actorId': string;
    /**
     * Actor email
     */
    'actorEmail': string;
    /**
     * Action performed
     */
    'action': string;
    /**
     * Target entity type
     */
    'targetType'?: string;
    /**
     * Target entity ID
     */
    'targetId'?: string;
    /**
     * HTTP status code
     */
    'statusCode'?: number;
    /**
     * Error message if any
     */
    'errorMessage'?: string;
    /**
     * IP address
     */
    'ipAddress'?: string;
    /**
     * User agent
     */
    'userAgent'?: string;
    /**
     * Additional metadata
     */
    'metadata'?: object;
    /**
     * Created timestamp
     */
    'createdAt': Date;
}

