/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AuditLogFiltersDto {
    /**
     * Filter by actor email
     */
    'actorEmail'?: string;
    /**
     * Filter by action type
     */
    'action'?: string;
    /**
     * Filter by target type
     */
    'targetType'?: string;
    /**
     * Filter by target ID
     */
    'targetId'?: string;
    /**
     * Filter by start date
     */
    'startDate'?: Date;
    /**
     * Filter by end date
     */
    'endDate'?: Date;
}

