/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AuditLogResponseDto
 */
export interface AuditLogResponseDto {
  /**
   * Audit log ID
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  id: string
  /**
   * Actor ID
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  actorId: string
  /**
   * Actor email
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  actorEmail: string
  /**
   * Action performed
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  action: string
  /**
   * Target entity type
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  targetType?: string
  /**
   * Target entity ID
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  targetId?: string
  /**
   * HTTP status code
   * @type {number}
   * @memberof AuditLogResponseDto
   */
  statusCode?: number
  /**
   * Error message if any
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  errorMessage?: string
  /**
   * IP address
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  ipAddress?: string
  /**
   * User agent
   * @type {string}
   * @memberof AuditLogResponseDto
   */
  userAgent?: string
  /**
   * Additional metadata
   * @type {object}
   * @memberof AuditLogResponseDto
   */
  metadata?: object
  /**
   * Created timestamp
   * @type {Date}
   * @memberof AuditLogResponseDto
   */
  createdAt: Date
}
