/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PermissionsDto } from './permissions-dto'

/**
 *
 * @export
 * @interface AuthUserDto
 */
export interface AuthUserDto {
  /**
   *
   * @type {string}
   * @memberof AuthUserDto
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof AuthUserDto
   */
  email: string
  /**
   *
   * @type {string}
   * @memberof AuthUserDto
   */
  name?: string
  /**
   *
   * @type {PermissionsDto}
   * @memberof AuthUserDto
   */
  permissions: PermissionsDto
}
