/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RegionQuotaCompositeKey } from './region-quota-composite-key';
// May contain unused imports in some cases
// @ts-ignore
import type { UpdateRegionQuotaDto } from './update-region-quota-dto';

export interface BulkUpdateRegionQuotaDto {
    'ids': Array<RegionQuotaCompositeKey>;
    /**
     * Updates to apply to all region quotas
     */
    'updates': UpdateRegionQuotaDto;
    'dryRun'?: boolean;
}

