/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UpdateOrganizationDto } from './update-organization-dto';

export interface BulkUpdateOrganizationDto {
    /**
     * Array of organization IDs to update
     */
    'ids': Array<string>;
    /**
     * Updates to apply to all organizations
     */
    'updates': UpdateOrganizationDto;
    /**
     * Dry run mode - validate without applying changes
     */
    'dryRun'?: boolean;
}

