/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationUserCompositeKey } from './organization-user-composite-key'
// May contain unused imports in some cases
// @ts-ignore
import type { UpdateOrganizationUserDto } from './update-organization-user-dto'

/**
 *
 * @export
 * @interface BulkUpdateOrganizationUserDto
 */
export interface BulkUpdateOrganizationUserDto {
  /**
   *
   * @type {Array<OrganizationUserCompositeKey>}
   * @memberof BulkUpdateOrganizationUserDto
   */
  ids: Array<OrganizationUserCompositeKey>
  /**
   * Updates to apply to all organization users
   * @type {UpdateOrganizationUserDto}
   * @memberof BulkUpdateOrganizationUserDto
   */
  updates: UpdateOrganizationUserDto
  /**
   *
   * @type {boolean}
   * @memberof BulkUpdateOrganizationUserDto
   */
  dryRun?: boolean
}
