/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BulkUpdateResponseDto } from './bulk-update-response-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { BulkUpdateResponseWrapperDtoError } from './bulk-update-response-wrapper-dto-error'

/**
 *
 * @export
 * @interface BulkUpdateResponseWrapperDto
 */
export interface BulkUpdateResponseWrapperDto {
  /**
   * Operation success status
   * @type {boolean}
   * @memberof BulkUpdateResponseWrapperDto
   */
  success: boolean
  /**
   * Bulk update results
   * @type {BulkUpdateResponseDto}
   * @memberof BulkUpdateResponseWrapperDto
   */
  data?: BulkUpdateResponseDto
  /**
   *
   * @type {BulkUpdateResponseWrapperDtoError}
   * @memberof BulkUpdateResponseWrapperDto
   */
  error?: BulkUpdateResponseWrapperDtoError
}
