/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BulkInsertResultDto } from './bulk-insert-result-dto'

/**
 *
 * @export
 * @interface BulkInsertResponseDto
 */
export interface BulkInsertResponseDto {
  /**
   * Total number of runners processed
   * @type {number}
   * @memberof BulkInsertResponseDto
   */
  totalProcessed: number
  /**
   * Number of successful inserts
   * @type {number}
   * @memberof BulkInsertResponseDto
   */
  successCount: number
  /**
   * Number of failed inserts
   * @type {number}
   * @memberof BulkInsertResponseDto
   */
  failureCount: number
  /**
   * Number of skipped (duplicate) runners
   * @type {number}
   * @memberof BulkInsertResponseDto
   */
  skippedCount: number
  /**
   * Array of individual insert results
   * @type {Array<BulkInsertResultDto>}
   * @memberof BulkInsertResponseDto
   */
  results: Array<BulkInsertResultDto>
  /**
   * Array of warning messages
   * @type {Array<string>}
   * @memberof BulkInsertResponseDto
   */
  warnings: Array<string>
}
