/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UpdateRunnerDto } from './update-runner-dto'

/**
 *
 * @export
 * @interface BulkUpdateRunnerDto
 */
export interface BulkUpdateRunnerDto {
  /**
   *
   * @type {Array<string>}
   * @memberof BulkUpdateRunnerDto
   */
  ids: Array<string>
  /**
   * Updates to apply to all runners
   * @type {UpdateRunnerDto}
   * @memberof BulkUpdateRunnerDto
   */
  updates: UpdateRunnerDto
  /**
   *
   * @type {boolean}
   * @memberof BulkUpdateRunnerDto
   */
  dryRun?: boolean
}
