/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateQuotaRequestDto {
    /**
     * Organization ID (UUID)
     */
    'organizationId': string;
    /**
     * Region ID (e.g. \"us\", \"eu\")
     */
    'regionId': string;
    /**
     * Sandbox class of the quota. Defaults to \"container\".
     */
    'sandboxClass'?: CreateQuotaRequestDtoSandboxClassEnum;
    /**
     * Why this quota is needed (shown to approvers)
     */
    'reason'?: string;
}

export const CreateQuotaRequestDtoSandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
    WINDOWS: 'windows',
} as const;

export type CreateQuotaRequestDtoSandboxClassEnum = typeof CreateQuotaRequestDtoSandboxClassEnum[keyof typeof CreateQuotaRequestDtoSandboxClassEnum];


