/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateQuotaBumpDto {
    /**
     * Organization ID (UUID)
     */
    'organizationId': string;
    /**
     * Region ID (e.g. \"us\", \"eu\")
     */
    'regionId': string;
    /**
     * Sandbox class of the quota to bump. Defaults to \"container\".
     */
    'sandboxClass'?: CreateQuotaBumpDtoSandboxClassEnum;
    /**
     * CPU cores to add to totalCpuQuota
     */
    'cpuDelta'?: number;
    /**
     * Memory (GiB) to add to totalMemoryQuota
     */
    'memoryDelta'?: number;
    /**
     * Disk (GiB) to add to totalDiskQuota
     */
    'diskDelta'?: number;
    /**
     * Why this bump is needed (shown to approvers)
     */
    'reason'?: string;
}

export const CreateQuotaBumpDtoSandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
    WINDOWS: 'windows',
} as const;

export type CreateQuotaBumpDtoSandboxClassEnum = typeof CreateQuotaBumpDtoSandboxClassEnum[keyof typeof CreateQuotaBumpDtoSandboxClassEnum];


