/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateRunnerDto {
    /**
     * Runner domain name
     */
    'domain': string;
    /**
     * Runner API key
     */
    'apiKey': string;
    /**
     * Region ID
     */
    'region': string;
    /**
     * CPU cores
     */
    'cpu': number;
    /**
     * Memory in GB
     */
    'memoryGiB': number;
    /**
     * Disk in GB
     */
    'diskGiB': number;
    /**
     * Sandbox class
     */
    'sandboxClass': CreateRunnerDtoSandboxClassEnum;
    /**
     * GPU count
     */
    'gpu'?: number;
    /**
     * GPU type
     */
    'gpuType'?: string;
    /**
     * Runner state
     */
    'state'?: CreateRunnerDtoStateEnum;
    /**
     * Is runner unschedulable
     */
    'unschedulable'?: boolean;
    /**
     * Runner API version. \"0\" uses domain-derived API/proxy URLs, \"2\" is reverse-tunneled.
     */
    'apiVersion'?: CreateRunnerDtoApiVersionEnum;
}

export const CreateRunnerDtoSandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
} as const;

export type CreateRunnerDtoSandboxClassEnum = typeof CreateRunnerDtoSandboxClassEnum[keyof typeof CreateRunnerDtoSandboxClassEnum];
export const CreateRunnerDtoStateEnum = {
    INITIALIZING: 'initializing',
    READY: 'ready',
    DISABLED: 'disabled',
    DECOMMISSIONED: 'decommissioned',
    UNRESPONSIVE: 'unresponsive',
} as const;

export type CreateRunnerDtoStateEnum = typeof CreateRunnerDtoStateEnum[keyof typeof CreateRunnerDtoStateEnum];
export const CreateRunnerDtoApiVersionEnum = {
    _0: '0',
    _2: '2',
} as const;

export type CreateRunnerDtoApiVersionEnum = typeof CreateRunnerDtoApiVersionEnum[keyof typeof CreateRunnerDtoApiVersionEnum];


