/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateRunnerDto {
    /**
     * Runner domain name
     */
    'domain': string;
    /**
     * Runner API key
     */
    'apiKey': string;
    /**
     * Region ID
     */
    'region': string;
    /**
     * CPU cores
     */
    'cpu': number;
    /**
     * Memory in GB
     */
    'memoryGiB': number;
    /**
     * Disk in GB
     */
    'diskGiB': number;
    /**
     * Sandbox class
     */
    'class': CreateRunnerDtoClassEnum;
    /**
     * GPU count
     */
    'gpu'?: number;
    /**
     * GPU type
     */
    'gpuType'?: string;
    /**
     * Runner state
     */
    'state'?: CreateRunnerDtoStateEnum;
    /**
     * Is runner unschedulable
     */
    'unschedulable'?: boolean;
}

export const CreateRunnerDtoClassEnum = {
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
} as const;

export type CreateRunnerDtoClassEnum = typeof CreateRunnerDtoClassEnum[keyof typeof CreateRunnerDtoClassEnum];
export const CreateRunnerDtoStateEnum = {
    INITIALIZING: 'initializing',
    READY: 'ready',
    DISABLED: 'disabled',
    DECOMMISSIONED: 'decommissioned',
    UNRESPONSIVE: 'unresponsive',
} as const;

export type CreateRunnerDtoStateEnum = typeof CreateRunnerDtoStateEnum[keyof typeof CreateRunnerDtoStateEnum];


