/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateRegionQuotaDto {
    /**
     * Organization ID (UUID)
     */
    'organizationId': string;
    /**
     * Region ID (e.g. \"us\", \"eu\")
     */
    'regionId': string;
    /**
     * Total CPU quota for the region
     */
    'totalCpuQuota': number;
    /**
     * Total memory quota (GB) for the region
     */
    'totalMemoryQuota': number;
    /**
     * Total disk quota (GB) for the region
     */
    'totalDiskQuota': number;
    /**
     * Max CPU per sandbox in this region. null = use organization default.
     */
    'maxCpuPerSandbox'?: number | null;
    /**
     * Max memory (GB) per sandbox in this region. null = use organization default.
     */
    'maxMemoryPerSandbox'?: number | null;
    /**
     * Max disk (GB) per sandbox in this region. null = use organization default.
     */
    'maxDiskPerSandbox'?: number | null;
    /**
     * Max disk (GB) for non-ephemeral sandboxes. null = fall back to maxDiskPerSandbox. 0 = disabled in this region.
     */
    'maxDiskPerNonEphemeralSandbox'?: number | null;
}

