/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MaintenanceType } from './maintenance-type';

export interface CreateMaintenanceRequestDto {
    'title': string;
    'description'?: string;
    'type': MaintenanceType;
    /**
     * Targeted inventory hostnames
     */
    'runnerNames': Array<string>;
    /**
     * Who asked for the work
     */
    'requestedBy': string;
    /**
     * 0 = p0 (most urgent) … 3 = p3; defaults to 2
     */
    'priority'?: number;
}



