/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ClickhouseOverrideDto } from './clickhouse-override-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { DatabaseOverrideDto } from './database-override-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { GrafanaOverrideDto } from './grafana-override-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { OpensearchOverrideDto } from './opensearch-override-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PosthogOverrideDto } from './posthog-override-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxOverrideDto } from './sandbox-override-dto';

export interface DatasourceOverridesDto {
    'database'?: DatabaseOverrideDto;
    'clickhouse'?: ClickhouseOverrideDto;
    'opensearch'?: OpensearchOverrideDto;
    'grafana'?: GrafanaOverrideDto;
    'posthog'?: PosthogOverrideDto;
    'sandbox'?: SandboxOverrideDto;
}

