/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const DiscrepancyKind = {
    NOT_IN_PROD: 'not_in_prod',
    PROD_ONLY: 'prod_only',
    DISABLED_BUT_ACTIVE: 'disabled_but_active',
    UNRESPONSIVE: 'unresponsive',
} as const;

export type DiscrepancyKind = typeof DiscrepancyKind[keyof typeof DiscrepancyKind];



