/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ExecutedActionsDto
 */
export interface ExecutedActionsDto {
  /**
   * Number of sandboxes destroyed
   * @type {number}
   * @memberof ExecutedActionsDto
   */
  sandboxesDestroyed: number
  /**
   * Number of snapshots deactivated
   * @type {number}
   * @memberof ExecutedActionsDto
   */
  snapshotsDeactivated: number
  /**
   * Number of organizations anonymized
   * @type {number}
   * @memberof ExecutedActionsDto
   */
  organizationsAnonymized: number
  /**
   * Whether user was anonymized (ID changed from \"userId\" to \"DELETED_userId\")
   * @type {boolean}
   * @memberof ExecutedActionsDto
   */
  userAnonymized: boolean
  /**
   * Number of sandbox templates deleted
   * @type {number}
   * @memberof ExecutedActionsDto
   */
  sandboxTemplatesDeleted?: number
  /**
   * Number of API keys deleted
   * @type {number}
   * @memberof ExecutedActionsDto
   */
  apiKeysDeleted?: number
  /**
   * Number of organization memberships deleted
   * @type {number}
   * @memberof ExecutedActionsDto
   */
  membershipsDeleted?: number
}
