/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DrainStatusDto } from './drain-status-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { MaintenanceRequestDto } from './maintenance-request-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ProdRunnerDto } from './prod-runner-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { RunnerEventDto } from './runner-event-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxStateCountDto } from './sandbox-state-count-dto';

export interface FleetRunnerDetailDto {
    'name': string;
    'source': string;
    'enabled': boolean;
    'env': string;
    'provider': string | null;
    'serverType': string | null;
    'os': string | null;
    'ip': string | null;
    'geo': string | null;
    'region': string | null;
    'location': string | null;
    'model': string | null;
    'nicSpeed': string | null;
    'monthlyCost': string | null;
    'hourlyCost': string | null;
    'tenant': string | null;
    'gpu': boolean;
    'groups': Array<string>;
    'domain': string | null;
    'provisionedAt': Date | null;
    'removedAt': Date | null;
    'lastSyncAt': Date;
    'prod': ProdRunnerDto | null;
    'activeSandboxes': number;
    'openRequests': number;
    'sandboxStates': Array<SandboxStateCountDto>;
    'drain': DrainStatusDto | null;
    'requests': Array<MaintenanceRequestDto>;
    'events': Array<RunnerEventDto>;
}

