/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface FleetRunnerFiltersDto {
    /**
     * Matches name, ip or domain
     */
    'search'?: string;
    'env'?: string;
    'provider'?: string;
    /**
     * Inventory region (region or location)
     */
    'invRegion'?: string;
    /**
     * Production region label
     */
    'prodRegion'?: string;
    'tenant'?: string;
    /**
     * Production state, or \'missing\' for runners without a prod row
     */
    'prodState'?: string;
    'enabledOnly'?: boolean;
    'gpuOnly'?: boolean;
    /**
     * Include runners removed from the inventory
     */
    'includeRemoved'?: boolean;
}

