/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MaintenanceStatus } from './maintenance-status';
// May contain unused imports in some cases
// @ts-ignore
import type { MaintenanceType } from './maintenance-type';

export interface MaintenanceRequestDto {
    'id': string;
    'title': string;
    'description': string;
    'type': MaintenanceType;
    'status': MaintenanceStatus;
    'runnerNames': Array<string>;
    'requestedBy': string;
    'createdBy': string;
    /**
     * 0 = p0 (most urgent) … 3 = p3
     */
    'priority': number;
    'closedAt': Date | null;
    'createdAt': Date;
    'updatedAt': Date;
    'allowedTransitions': Array<MaintenanceStatus>;
}



