/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const MaintenanceStatus = {
    REQUESTED: 'requested',
    ACKNOWLEDGED: 'acknowledged',
    DRAINING: 'draining',
    READY_FOR_MAINTENANCE: 'ready_for_maintenance',
    IN_MAINTENANCE: 'in_maintenance',
    RESTORED: 'restored',
    CLOSED: 'closed',
    CANCELLED: 'cancelled',
} as const;

export type MaintenanceStatus = typeof MaintenanceStatus[keyof typeof MaintenanceStatus];



