/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationUserFiltersDto
 */
export interface OrganizationUserFiltersDto {
  /**
   * Search by user ID or organization ID (partial match)
   * @type {string}
   * @memberof OrganizationUserFiltersDto
   */
  search?: string
  /**
   * Filter by organization ID
   * @type {string}
   * @memberof OrganizationUserFiltersDto
   */
  organizationId?: string
  /**
   * Filter by user ID
   * @type {string}
   * @memberof OrganizationUserFiltersDto
   */
  userId?: string
  /**
   * Filter by role
   * @type {Array<string>}
   * @memberof OrganizationUserFiltersDto
   */
  role?: Array<OrganizationUserFiltersDtoRoleEnum>
  /**
   * Filter by created after date
   * @type {Date}
   * @memberof OrganizationUserFiltersDto
   */
  createdAfter?: Date
  /**
   * Filter by created before date
   * @type {Date}
   * @memberof OrganizationUserFiltersDto
   */
  createdBefore?: Date
}

export const OrganizationUserFiltersDtoRoleEnum = {
  OWNER: 'owner',
  MEMBER: 'member',
} as const

export type OrganizationUserFiltersDtoRoleEnum =
  (typeof OrganizationUserFiltersDtoRoleEnum)[keyof typeof OrganizationUserFiltersDtoRoleEnum]
