/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationFiltersDto
 */
export interface OrganizationFiltersDto {
  /**
   * Search by name or id (partial match)
   * @type {string}
   * @memberof OrganizationFiltersDto
   */
  search?: string
  /**
   * Filter by organization name (partial match)
   * @type {string}
   * @memberof OrganizationFiltersDto
   */
  name?: string
  /**
   * Filter by personal organizations
   * @type {boolean}
   * @memberof OrganizationFiltersDto
   */
  personal?: boolean
  /**
   * Filter by suspended status
   * @type {boolean}
   * @memberof OrganizationFiltersDto
   */
  suspended?: boolean
  /**
   * Filter by telemetry enabled
   * @type {boolean}
   * @memberof OrganizationFiltersDto
   */
  telemetryEnabled?: boolean
  /**
   * Filter by creator user ID
   * @type {string}
   * @memberof OrganizationFiltersDto
   */
  createdBy?: string
  /**
   * Filter by created after date
   * @type {Date}
   * @memberof OrganizationFiltersDto
   */
  createdAfter?: Date
  /**
   * Filter by created before date
   * @type {Date}
   * @memberof OrganizationFiltersDto
   */
  createdBefore?: Date
  /**
   * Filter by suspended after date
   * @type {Date}
   * @memberof OrganizationFiltersDto
   */
  suspendedAfter?: Date
  /**
   * Filter by suspended before date
   * @type {Date}
   * @memberof OrganizationFiltersDto
   */
  suspendedBefore?: Date
}
