/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationUserResponseDto
 */
export interface OrganizationUserResponseDto {
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponseDto
   */
  organizationId: string
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponseDto
   */
  userId: string
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponseDto
   */
  role: OrganizationUserResponseDtoRoleEnum
  /**
   *
   * @type {Date}
   * @memberof OrganizationUserResponseDto
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof OrganizationUserResponseDto
   */
  updatedAt: Date
  /**
   *
   * @type {string}
   * @memberof OrganizationUserResponseDto
   */
  userEmail?: string
}

export const OrganizationUserResponseDtoRoleEnum = {
  OWNER: 'owner',
  MEMBER: 'member',
} as const

export type OrganizationUserResponseDtoRoleEnum =
  (typeof OrganizationUserResponseDtoRoleEnum)[keyof typeof OrganizationUserResponseDtoRoleEnum]
