/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OrganizationFiltersDto {
    /**
     * Search by name or id (partial match)
     */
    'search'?: string;
    /**
     * Filter by organization name (partial match)
     */
    'name'?: string;
    /**
     * Filter by personal organizations
     */
    'personal'?: boolean;
    /**
     * Filter by suspended status
     */
    'suspended'?: boolean;
    /**
     * Filter by telemetry enabled
     */
    'telemetryEnabled'?: boolean;
    /**
     * Filter by creator user ID
     */
    'createdBy'?: string;
    /**
     * Filter by created after date
     */
    'createdAfter'?: Date;
    /**
     * Filter by created before date
     */
    'createdBefore'?: Date;
    /**
     * Filter by suspended after date
     */
    'suspendedAfter'?: Date;
    /**
     * Filter by suspended before date
     */
    'suspendedBefore'?: Date;
}

