/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OrganizationResponseDto {
    /**
     * Organization ID
     */
    'id': string;
    /**
     * Organization name
     */
    'name': string;
    /**
     * Created by user ID
     */
    'createdBy': string;
    /**
     * Is personal organization
     */
    'personal': boolean;
    /**
     * Telemetry enabled
     */
    'telemetryEnabled': boolean;
    /**
     * Is suspended
     */
    'suspended': boolean;
    /**
     * Suspended at
     */
    'suspendedAt'?: Date;
    /**
     * Created at
     */
    'createdAt': Date;
    /**
     * Default region ID
     */
    'defaultRegionId'?: string;
    /**
     * Max CPU per sandbox
     */
    'maxCpuPerSandbox': number;
    /**
     * Max memory per sandbox in GB
     */
    'maxMemoryPerSandbox': number;
    /**
     * Max disk per sandbox in GB
     */
    'maxDiskPerSandbox': number;
    /**
     * Max snapshot size in GB
     */
    'maxSnapshotSize': number;
    /**
     * Snapshot quota in GB
     */
    'snapshotQuota': number;
    /**
     * Volume quota in GB
     */
    'volumeQuota': number;
    /**
     * Limit network egress for sandboxes
     */
    'sandboxLimitedNetworkEgress': boolean;
    /**
     * Suspended until date
     */
    'suspendedUntil'?: Date;
    /**
     * Suspension reason
     */
    'suspensionReason'?: string;
    /**
     * Suspension cleanup grace period in hours
     */
    'suspensionCleanupGracePeriodHours': number;
    /**
     * Authenticated rate limit
     */
    'authenticatedRateLimit'?: number;
    /**
     * Sandbox create rate limit
     */
    'sandboxCreateRateLimit'?: number;
    /**
     * Sandbox lifecycle rate limit
     */
    'sandboxLifecycleRateLimit'?: number;
    /**
     * Authenticated rate limit TTL in seconds
     */
    'authenticatedRateLimitTtlSeconds'?: number;
    /**
     * Sandbox create rate limit TTL in seconds
     */
    'sandboxCreateRateLimitTtlSeconds'?: number;
    /**
     * Sandbox lifecycle rate limit TTL in seconds
     */
    'sandboxLifecycleRateLimitTtlSeconds'?: number;
    /**
     * Snapshot deactivation timeout in minutes (default 20160 = 14 days)
     */
    'snapshotDeactivationTimeoutMinutes': number;
}

