/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OrganizationUserResponseDto {
    'organizationId': string;
    'userId': string;
    'role': OrganizationUserResponseDtoRoleEnum;
    'createdAt': Date;
    'updatedAt': Date;
    'userEmail'?: string;
}

export const OrganizationUserResponseDtoRoleEnum = {
    OWNER: 'owner',
    MEMBER: 'member',
} as const;

export type OrganizationUserResponseDtoRoleEnum = typeof OrganizationUserResponseDtoRoleEnum[keyof typeof OrganizationUserResponseDtoRoleEnum];


