/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface OrganizationUserFiltersDto {
    /**
     * Search by user ID or organization ID (partial match)
     */
    'search'?: string;
    /**
     * Filter by organization ID
     */
    'organizationId'?: string;
    /**
     * Filter by user ID
     */
    'userId'?: string;
    /**
     * Filter by role
     */
    'role'?: Array<OrganizationUserFiltersDtoRoleEnum>;
    /**
     * Filter by created after date
     */
    'createdAfter'?: Date;
    /**
     * Filter by created before date
     */
    'createdBefore'?: Date;
}

export const OrganizationUserFiltersDtoRoleEnum = {
    OWNER: 'owner',
    MEMBER: 'member',
} as const;

export type OrganizationUserFiltersDtoRoleEnum = typeof OrganizationUserFiltersDtoRoleEnum[keyof typeof OrganizationUserFiltersDtoRoleEnum];


