/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface OrganizationPreviewDto
 */
export interface OrganizationPreviewDto {
  /**
   * Organization ID
   * @type {string}
   * @memberof OrganizationPreviewDto
   */
  id: string
  /**
   * Organization name
   * @type {string}
   * @memberof OrganizationPreviewDto
   */
  name: string
  /**
   * User role in organization
   * @type {string}
   * @memberof OrganizationPreviewDto
   */
  role: string
}
