/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PaginationResponseDto
 */
export interface PaginationResponseDto {
  /**
   * Current page number
   * @type {number}
   * @memberof PaginationResponseDto
   */
  page?: number
  /**
   * Items per page
   * @type {number}
   * @memberof PaginationResponseDto
   */
  pageSize?: number
  /**
   * Total number of items
   * @type {number}
   * @memberof PaginationResponseDto
   */
  total?: number
  /**
   * Total number of pages
   * @type {number}
   * @memberof PaginationResponseDto
   */
  totalPages?: number
}
