/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { UpdateSandboxDto } from './update-sandbox-dto'

/**
 *
 * @export
 * @interface PatchSandboxDto
 */
export interface PatchSandboxDto {
  /**
   * Fields to update
   * @type {UpdateSandboxDto}
   * @memberof PatchSandboxDto
   */
  updates: UpdateSandboxDto
  /**
   * Expected current values for optimistic concurrency control. Update fails with 409 if any field does not match.
   * @type {UpdateSandboxDto}
   * @memberof PatchSandboxDto
   */
  preconditions?: UpdateSandboxDto
}
