/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UpdateRegionQuotaDto } from './update-region-quota-dto';

export interface PatchRegionQuotaDto {
    /**
     * Sandbox class of the quota row to update. Defaults to \"container\".
     */
    'sandboxClass'?: PatchRegionQuotaDtoSandboxClassEnum;
    /**
     * Fields to update
     */
    'updates': UpdateRegionQuotaDto;
    /**
     * Expected current values for optimistic concurrency control. Update fails with 409 if any field does not match.
     */
    'preconditions'?: UpdateRegionQuotaDto;
}

export const PatchRegionQuotaDtoSandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
    WINDOWS: 'windows',
} as const;

export type PatchRegionQuotaDtoSandboxClassEnum = typeof PatchRegionQuotaDtoSandboxClassEnum[keyof typeof PatchRegionQuotaDtoSandboxClassEnum];


