/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PermissionsDto
 */
export interface PermissionsDto {
  /**
   * Bypasses all permission checks.
   * @type {boolean}
   * @memberof PermissionsDto
   */
  superAdmin?: boolean
  /**
   *
   * @type {Array<string>}
   * @memberof PermissionsDto
   */
  sandboxes?: Array<PermissionsDtoSandboxesEnum>
  /**
   *
   * @type {Array<string>}
   * @memberof PermissionsDto
   */
  snapshots?: Array<PermissionsDtoSnapshotsEnum>
  /**
   *
   * @type {Array<string>}
   * @memberof PermissionsDto
   */
  runners?: Array<PermissionsDtoRunnersEnum>
  /**
   *
   * @type {Array<string>}
   * @memberof PermissionsDto
   */
  organizations?: Array<PermissionsDtoOrganizationsEnum>
  /**
   *
   * @type {Array<string>}
   * @memberof PermissionsDto
   */
  organizationUsers?: Array<PermissionsDtoOrganizationUsersEnum>
  /**
   *
   * @type {Array<string>}
   * @memberof PermissionsDto
   */
  regionQuotas?: Array<PermissionsDtoRegionQuotasEnum>
  /**
   *
   * @type {Array<string>}
   * @memberof PermissionsDto
   */
  users?: Array<PermissionsDtoUsersEnum>
  /**
   *
   * @type {Array<string>}
   * @memberof PermissionsDto
   */
  auditLogs?: Array<PermissionsDtoAuditLogsEnum>
}

export const PermissionsDtoSandboxesEnum = {
  READ: 'read',
  WRITE: 'write',
  WRITE_BULK: 'write-bulk',
  DELETE: 'delete',
} as const

export type PermissionsDtoSandboxesEnum = (typeof PermissionsDtoSandboxesEnum)[keyof typeof PermissionsDtoSandboxesEnum]
export const PermissionsDtoSnapshotsEnum = {
  READ: 'read',
  WRITE: 'write',
  WRITE_BULK: 'write-bulk',
  DELETE: 'delete',
} as const

export type PermissionsDtoSnapshotsEnum = (typeof PermissionsDtoSnapshotsEnum)[keyof typeof PermissionsDtoSnapshotsEnum]
export const PermissionsDtoRunnersEnum = {
  READ: 'read',
  WRITE: 'write',
  WRITE_BULK: 'write-bulk',
  DELETE: 'delete',
} as const

export type PermissionsDtoRunnersEnum = (typeof PermissionsDtoRunnersEnum)[keyof typeof PermissionsDtoRunnersEnum]
export const PermissionsDtoOrganizationsEnum = {
  READ: 'read',
  WRITE: 'write',
  WRITE_BULK: 'write-bulk',
  DELETE: 'delete',
} as const

export type PermissionsDtoOrganizationsEnum =
  (typeof PermissionsDtoOrganizationsEnum)[keyof typeof PermissionsDtoOrganizationsEnum]
export const PermissionsDtoOrganizationUsersEnum = {
  READ: 'read',
  WRITE: 'write',
  WRITE_BULK: 'write-bulk',
  DELETE: 'delete',
} as const

export type PermissionsDtoOrganizationUsersEnum =
  (typeof PermissionsDtoOrganizationUsersEnum)[keyof typeof PermissionsDtoOrganizationUsersEnum]
export const PermissionsDtoRegionQuotasEnum = {
  READ: 'read',
  WRITE: 'write',
  WRITE_BULK: 'write-bulk',
  DELETE: 'delete',
} as const

export type PermissionsDtoRegionQuotasEnum =
  (typeof PermissionsDtoRegionQuotasEnum)[keyof typeof PermissionsDtoRegionQuotasEnum]
export const PermissionsDtoUsersEnum = {
  READ: 'read',
  DELETE: 'delete',
} as const

export type PermissionsDtoUsersEnum = (typeof PermissionsDtoUsersEnum)[keyof typeof PermissionsDtoUsersEnum]
export const PermissionsDtoAuditLogsEnum = {
  READ: 'read',
} as const

export type PermissionsDtoAuditLogsEnum = (typeof PermissionsDtoAuditLogsEnum)[keyof typeof PermissionsDtoAuditLogsEnum]
