/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface PermissionsDto {
    /**
     * Bypasses all permission checks.
     */
    'superAdmin'?: boolean;
    'sandboxes'?: Array<PermissionsDtoSandboxesEnum>;
    'snapshots'?: Array<PermissionsDtoSnapshotsEnum>;
    'runners'?: Array<PermissionsDtoRunnersEnum>;
    'fleet'?: Array<PermissionsDtoFleetEnum>;
    'organizations'?: Array<PermissionsDtoOrganizationsEnum>;
    'organizationUsers'?: Array<PermissionsDtoOrganizationUsersEnum>;
    'regionQuotas'?: Array<PermissionsDtoRegionQuotasEnum>;
    'users'?: Array<PermissionsDtoUsersEnum>;
    'auditLogs'?: Array<PermissionsDtoAuditLogsEnum>;
    'maliDatasources'?: Array<PermissionsDtoMaliDatasourcesEnum>;
}

export const PermissionsDtoSandboxesEnum = {
    READ: 'read',
    WRITE: 'write',
    WRITE_BULK: 'write-bulk',
    DELETE: 'delete',
    RESYNC: 'resync',
} as const;

export type PermissionsDtoSandboxesEnum = typeof PermissionsDtoSandboxesEnum[keyof typeof PermissionsDtoSandboxesEnum];
export const PermissionsDtoSnapshotsEnum = {
    READ: 'read',
    WRITE: 'write',
    WRITE_BULK: 'write-bulk',
    DELETE: 'delete',
} as const;

export type PermissionsDtoSnapshotsEnum = typeof PermissionsDtoSnapshotsEnum[keyof typeof PermissionsDtoSnapshotsEnum];
export const PermissionsDtoRunnersEnum = {
    READ: 'read',
    WRITE: 'write',
    WRITE_BULK: 'write-bulk',
    DELETE: 'delete',
} as const;

export type PermissionsDtoRunnersEnum = typeof PermissionsDtoRunnersEnum[keyof typeof PermissionsDtoRunnersEnum];
export const PermissionsDtoFleetEnum = {
    READ: 'read',
    WRITE: 'write',
} as const;

export type PermissionsDtoFleetEnum = typeof PermissionsDtoFleetEnum[keyof typeof PermissionsDtoFleetEnum];
export const PermissionsDtoOrganizationsEnum = {
    READ: 'read',
    WRITE: 'write',
    WRITE_BULK: 'write-bulk',
    DELETE: 'delete',
} as const;

export type PermissionsDtoOrganizationsEnum = typeof PermissionsDtoOrganizationsEnum[keyof typeof PermissionsDtoOrganizationsEnum];
export const PermissionsDtoOrganizationUsersEnum = {
    READ: 'read',
    WRITE: 'write',
    WRITE_BULK: 'write-bulk',
    DELETE: 'delete',
} as const;

export type PermissionsDtoOrganizationUsersEnum = typeof PermissionsDtoOrganizationUsersEnum[keyof typeof PermissionsDtoOrganizationUsersEnum];
export const PermissionsDtoRegionQuotasEnum = {
    READ: 'read',
    WRITE: 'write',
    WRITE_BULK: 'write-bulk',
    DELETE: 'delete',
    REQUEST: 'request',
} as const;

export type PermissionsDtoRegionQuotasEnum = typeof PermissionsDtoRegionQuotasEnum[keyof typeof PermissionsDtoRegionQuotasEnum];
export const PermissionsDtoUsersEnum = {
    READ: 'read',
    DELETE: 'delete',
} as const;

export type PermissionsDtoUsersEnum = typeof PermissionsDtoUsersEnum[keyof typeof PermissionsDtoUsersEnum];
export const PermissionsDtoAuditLogsEnum = {
    READ: 'read',
} as const;

export type PermissionsDtoAuditLogsEnum = typeof PermissionsDtoAuditLogsEnum[keyof typeof PermissionsDtoAuditLogsEnum];
export const PermissionsDtoMaliDatasourcesEnum = {
    DATABASE: 'database',
    CLICKHOUSE: 'clickhouse',
    GRAFANA: 'grafana',
    OPENSEARCH: 'opensearch',
    POSTHOG: 'posthog',
    SANDBOX: 'sandbox',
} as const;

export type PermissionsDtoMaliDatasourcesEnum = typeof PermissionsDtoMaliDatasourcesEnum[keyof typeof PermissionsDtoMaliDatasourcesEnum];


