/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProdRunnerDto {
    'id': string;
    'domain': string | null;
    'region': string;
    'state': string;
    'unschedulable': boolean;
    'draining': boolean;
    'availabilityScore': number;
    'sandboxClass': string;
    'cpu': number;
    'memoryGiB': number;
    'diskGiB': number;
    'gpu': number | null;
    'gpuType': string | null;
    'currentCpuUsagePercentage': number;
    'currentMemoryUsagePercentage': number;
    'currentDiskUsagePercentage': number;
    'currentAllocatedCpu': number;
    'currentStartedSandboxes': number;
    'currentSnapshotCount': number;
    'lastChecked': Date | null;
    'appVersion': string | null;
    'createdAt': Date;
}

