/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RangeDto } from './range-dto'

/**
 *
 * @export
 * @interface RegionQuotaFiltersDto
 */
export interface RegionQuotaFiltersDto {
  /**
   * Search by organization name or id (partial match)
   * @type {string}
   * @memberof RegionQuotaFiltersDto
   */
  search?: string
  /**
   * Filter by organization ID
   * @type {string}
   * @memberof RegionQuotaFiltersDto
   */
  organizationId?: string
  /**
   * Filter by organization name
   * @type {string}
   * @memberof RegionQuotaFiltersDto
   */
  organizationName?: string
  /**
   * Filter by region ID
   * @type {string}
   * @memberof RegionQuotaFiltersDto
   */
  regionId?: string
  /**
   * Filter by CPU quota range
   * @type {RangeDto}
   * @memberof RegionQuotaFiltersDto
   */
  cpuQuota?: RangeDto
  /**
   * Filter by memory quota range
   * @type {RangeDto}
   * @memberof RegionQuotaFiltersDto
   */
  memoryQuota?: RangeDto
  /**
   * Filter by disk quota range
   * @type {RangeDto}
   * @memberof RegionQuotaFiltersDto
   */
  diskQuota?: RangeDto
}
