/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RangeDto } from './range-dto';

export interface RegionQuotaFiltersDto {
    /**
     * Search by organization name or id (partial match)
     */
    'search'?: string;
    /**
     * Filter by organization ID
     */
    'organizationId'?: string;
    /**
     * Filter by organization name
     */
    'organizationName'?: string;
    /**
     * Filter by region ID
     */
    'regionId'?: string;
    /**
     * Filter by CPU quota range
     */
    'cpuQuota'?: RangeDto;
    /**
     * Filter by memory quota range
     */
    'memoryQuota'?: RangeDto;
    /**
     * Filter by disk quota range
     */
    'diskQuota'?: RangeDto;
}

