/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RegionQuotaCompositeKey {
    'organizationId': string;
    'region': string;
    /**
     * Sandbox class; defaults to \"container\" when omitted
     */
    'sandboxClass'?: RegionQuotaCompositeKeySandboxClassEnum;
}

export const RegionQuotaCompositeKeySandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
    WINDOWS: 'windows',
} as const;

export type RegionQuotaCompositeKeySandboxClassEnum = typeof RegionQuotaCompositeKeySandboxClassEnum[keyof typeof RegionQuotaCompositeKeySandboxClassEnum];


