/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RegionQuotaResponseDto {
    'organizationId': string;
    'regionId': string;
    'sandboxClass': RegionQuotaResponseDtoSandboxClassEnum;
    'totalCpuQuota': number;
    'totalMemoryQuota': number;
    'totalDiskQuota': number;
    'maxCpuPerSandbox'?: number | null;
    'maxMemoryPerSandbox'?: number | null;
    'maxDiskPerSandbox'?: number | null;
    'maxDiskPerNonEphemeralSandbox'?: number | null;
    'sandboxQuota'?: number;
    'createdAt': Date;
    'updatedAt': Date;
    'organizationName'?: string;
}

export const RegionQuotaResponseDtoSandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
    WINDOWS: 'windows',
} as const;

export type RegionQuotaResponseDtoSandboxClassEnum = typeof RegionQuotaResponseDtoSandboxClassEnum[keyof typeof RegionQuotaResponseDtoSandboxClassEnum];


