/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RegionQuotaResponseDto
 */
export interface RegionQuotaResponseDto {
  /**
   *
   * @type {string}
   * @memberof RegionQuotaResponseDto
   */
  organizationId: string
  /**
   *
   * @type {string}
   * @memberof RegionQuotaResponseDto
   */
  regionId: string
  /**
   *
   * @type {number}
   * @memberof RegionQuotaResponseDto
   */
  totalCpuQuota: number
  /**
   *
   * @type {number}
   * @memberof RegionQuotaResponseDto
   */
  totalMemoryQuota: number
  /**
   *
   * @type {number}
   * @memberof RegionQuotaResponseDto
   */
  totalDiskQuota: number
  /**
   *
   * @type {number}
   * @memberof RegionQuotaResponseDto
   */
  sandboxQuota?: number
  /**
   *
   * @type {Date}
   * @memberof RegionQuotaResponseDto
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof RegionQuotaResponseDto
   */
  updatedAt: Date
  /**
   *
   * @type {string}
   * @memberof RegionQuotaResponseDto
   */
  organizationName?: string
}
