/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const RunnerEventType = {
    INVENTORY_ADDED: 'inventory_added',
    INVENTORY_ENABLED: 'inventory_enabled',
    INVENTORY_DISABLED: 'inventory_disabled',
    INVENTORY_REMOVED: 'inventory_removed',
    REQUEST_CREATED: 'request_created',
    REQUEST_STATUS_CHANGED: 'request_status_changed',
    NOTE: 'note',
} as const;

export type RunnerEventType = typeof RunnerEventType[keyof typeof RunnerEventType];



