/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RunnerResponseDto {
    'id': string;
    'domain': string;
    'region': string;
    'state': RunnerResponseDtoStateEnum;
    'sandboxClass': RunnerResponseDtoSandboxClassEnum;
    'currentCpuUsagePercentage': number;
    'currentMemoryUsagePercentage': number;
    'currentDiskUsagePercentage': number;
    'availabilityScore'?: number;
    'cpu': number;
    'memoryGiB': number;
    'diskGiB': number;
    'gpu'?: number | null;
    'gpuType'?: RunnerResponseDtoGpuTypeEnum | null;
    'lastChecked'?: Date;
    'unschedulable': boolean;
    'draining': boolean;
    'appVersion'?: string | null;
    'apiVersion': string;
}

export const RunnerResponseDtoStateEnum = {
    INITIALIZING: 'initializing',
    READY: 'ready',
    DISABLED: 'disabled',
    DECOMMISSIONED: 'decommissioned',
    UNRESPONSIVE: 'unresponsive',
} as const;

export type RunnerResponseDtoStateEnum = typeof RunnerResponseDtoStateEnum[keyof typeof RunnerResponseDtoStateEnum];
export const RunnerResponseDtoSandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
    WINDOWS: 'windows',
} as const;

export type RunnerResponseDtoSandboxClassEnum = typeof RunnerResponseDtoSandboxClassEnum[keyof typeof RunnerResponseDtoSandboxClassEnum];
export const RunnerResponseDtoGpuTypeEnum = {
    H100: 'H100',
    H200: 'H200',
    RTX_PRO_6000: 'RTX-PRO-6000',
    RTX_4090: 'RTX-4090',
    RTX_5090: 'RTX-5090',
} as const;

export type RunnerResponseDtoGpuTypeEnum = typeof RunnerResponseDtoGpuTypeEnum[keyof typeof RunnerResponseDtoGpuTypeEnum];


