/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RunnerResponseDto {
    'id': string;
    'domain': string;
    'region': string;
    'state': RunnerResponseDtoStateEnum;
    'class': RunnerResponseDtoClassEnum;
    'currentCpuUsagePercentage': number;
    'currentMemoryUsagePercentage': number;
    'currentDiskUsagePercentage': number;
    'availabilityScore'?: number;
    'cpu': number;
    'memoryGiB': number;
    'diskGiB': number;
    'lastChecked'?: Date;
    'unschedulable': boolean;
    'draining': boolean;
    'appVersion'?: string | null;
    'apiVersion': string;
}

export const RunnerResponseDtoStateEnum = {
    INITIALIZING: 'initializing',
    READY: 'ready',
    DISABLED: 'disabled',
    DECOMMISSIONED: 'decommissioned',
    UNRESPONSIVE: 'unresponsive',
} as const;

export type RunnerResponseDtoStateEnum = typeof RunnerResponseDtoStateEnum[keyof typeof RunnerResponseDtoStateEnum];
export const RunnerResponseDtoClassEnum = {
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
} as const;

export type RunnerResponseDtoClassEnum = typeof RunnerResponseDtoClassEnum[keyof typeof RunnerResponseDtoClassEnum];


