/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RangeDto } from './range-dto';

export interface RunnerFiltersDto {
    /**
     * Search by domain or id (OR match)
     */
    'search'?: string;
    /**
     * Filter by region
     */
    'region'?: string;
    /**
     * Filter by runner state
     */
    'state'?: Array<RunnerFiltersDtoStateEnum>;
    /**
     * Filter by runner class
     */
    'class'?: Array<RunnerFiltersDtoClassEnum>;
    /**
     * Filter by unschedulable status
     */
    'unschedulable'?: boolean;
    /**
     * Filter by CPU usage percentage range
     */
    'cpuUsage'?: RangeDto;
    /**
     * Filter by memory usage percentage range
     */
    'memoryUsage'?: RangeDto;
    /**
     * Filter by disk usage percentage range
     */
    'diskUsage'?: RangeDto;
    /**
     * Filter by availability score range
     */
    'availabilityScore'?: RangeDto;
    /**
     * Filter by last checked after date
     */
    'lastCheckedAfter'?: Date;
    /**
     * Filter by last checked before date
     */
    'lastCheckedBefore'?: Date;
}

export const RunnerFiltersDtoStateEnum = {
    INITIALIZING: 'initializing',
    READY: 'ready',
    DISABLED: 'disabled',
    DECOMMISSIONED: 'decommissioned',
    UNRESPONSIVE: 'unresponsive',
} as const;

export type RunnerFiltersDtoStateEnum = typeof RunnerFiltersDtoStateEnum[keyof typeof RunnerFiltersDtoStateEnum];
export const RunnerFiltersDtoClassEnum = {
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
} as const;

export type RunnerFiltersDtoClassEnum = typeof RunnerFiltersDtoClassEnum[keyof typeof RunnerFiltersDtoClassEnum];


