/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RangeDto } from './range-dto'

/**
 *
 * @export
 * @interface SandboxFiltersDto
 */
export interface SandboxFiltersDto {
  /**
   * Filter by specific sandbox IDs
   * @type {Array<string>}
   * @memberof SandboxFiltersDto
   */
  sandboxIds?: Array<string>
  /**
   * Filter by organization ID
   * @type {string}
   * @memberof SandboxFiltersDto
   */
  organizationId?: string
  /**
   * Search by id (partial match)
   * @type {string}
   * @memberof SandboxFiltersDto
   */
  search?: string
  /**
   * Filter by region
   * @type {string}
   * @memberof SandboxFiltersDto
   */
  region?: string
  /**
   * Filter by sandbox states
   * @type {Array<string>}
   * @memberof SandboxFiltersDto
   */
  state?: Array<SandboxFiltersDtoStateEnum>
  /**
   * Exclude specific states
   * @type {Array<string>}
   * @memberof SandboxFiltersDto
   */
  excludeStates?: Array<SandboxFiltersDtoExcludeStatesEnum>
  /**
   * Filter by runner ID
   * @type {string}
   * @memberof SandboxFiltersDto
   */
  runnerId?: string
  /**
   * Filter by public status
   * @type {boolean}
   * @memberof SandboxFiltersDto
   */
  public?: boolean
  /**
   * Only include sandboxes with errors
   * @type {boolean}
   * @memberof SandboxFiltersDto
   */
  errorOnly?: boolean
  /**
   * Filter by has error status
   * @type {boolean}
   * @memberof SandboxFiltersDto
   */
  hasError?: boolean
  /**
   * Filter by CPU range
   * @type {RangeDto}
   * @memberof SandboxFiltersDto
   */
  cpu?: RangeDto
  /**
   * Filter by memory range
   * @type {RangeDto}
   * @memberof SandboxFiltersDto
   */
  memory?: RangeDto
  /**
   * Filter by disk range
   * @type {RangeDto}
   * @memberof SandboxFiltersDto
   */
  disk?: RangeDto
  /**
   * Filter by created after date
   * @type {Date}
   * @memberof SandboxFiltersDto
   */
  createdAfter?: Date
  /**
   * Filter by created before date
   * @type {Date}
   * @memberof SandboxFiltersDto
   */
  createdBefore?: Date
  /**
   * Filter by last activity after date
   * @type {Date}
   * @memberof SandboxFiltersDto
   */
  lastActivityAfter?: Date
  /**
   * Filter by last activity before date
   * @type {Date}
   * @memberof SandboxFiltersDto
   */
  lastActivityBefore?: Date
}

export const SandboxFiltersDtoStateEnum = {
  CREATING: 'creating',
  RESTORING: 'restoring',
  DESTROYED: 'destroyed',
  DESTROYING: 'destroying',
  STARTED: 'started',
  STOPPED: 'stopped',
  STARTING: 'starting',
  STOPPING: 'stopping',
  ERROR: 'error',
  BUILD_FAILED: 'build_failed',
  PENDING_BUILD: 'pending_build',
  BUILDING_SNAPSHOT: 'building_snapshot',
  UNKNOWN: 'unknown',
  PULLING_SNAPSHOT: 'pulling_snapshot',
  ARCHIVED: 'archived',
  ARCHIVING: 'archiving',
  RESIZING: 'resizing',
} as const

export type SandboxFiltersDtoStateEnum = (typeof SandboxFiltersDtoStateEnum)[keyof typeof SandboxFiltersDtoStateEnum]
export const SandboxFiltersDtoExcludeStatesEnum = {
  CREATING: 'creating',
  RESTORING: 'restoring',
  DESTROYED: 'destroyed',
  DESTROYING: 'destroying',
  STARTED: 'started',
  STOPPED: 'stopped',
  STARTING: 'starting',
  STOPPING: 'stopping',
  ERROR: 'error',
  BUILD_FAILED: 'build_failed',
  PENDING_BUILD: 'pending_build',
  BUILDING_SNAPSHOT: 'building_snapshot',
  UNKNOWN: 'unknown',
  PULLING_SNAPSHOT: 'pulling_snapshot',
  ARCHIVED: 'archived',
  ARCHIVING: 'archiving',
  RESIZING: 'resizing',
} as const

export type SandboxFiltersDtoExcludeStatesEnum =
  (typeof SandboxFiltersDtoExcludeStatesEnum)[keyof typeof SandboxFiltersDtoExcludeStatesEnum]
