/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SandboxResponseDto {
    'id': string;
    'name': string;
    'errorReason'?: string;
    'organizationId': string;
    'region': string;
    'state': SandboxResponseDtoStateEnum;
    'desiredState': SandboxResponseDtoDesiredStateEnum;
    'class': SandboxResponseDtoClassEnum;
    'runnerId'?: string;
    'labels': object;
    'cpu': number;
    'mem': number;
    'disk': number;
    'gpu': number;
    'createdAt': Date;
    'networkBlockAll': boolean;
    'networkAllowList'?: string;
    'backupState': SandboxResponseDtoBackupStateEnum;
    'backupErrorReason'?: string;
    'autoStopInterval': number;
    'autoArchiveInterval': number;
    'autoDeleteInterval': number;
    'pending': boolean;
    'recoverable': boolean;
    'public': boolean;
}

export const SandboxResponseDtoStateEnum = {
    CREATING: 'creating',
    RESTORING: 'restoring',
    DESTROYED: 'destroyed',
    DESTROYING: 'destroying',
    STARTED: 'started',
    STOPPED: 'stopped',
    STARTING: 'starting',
    STOPPING: 'stopping',
    ERROR: 'error',
    BUILD_FAILED: 'build_failed',
    PENDING_BUILD: 'pending_build',
    BUILDING_SNAPSHOT: 'building_snapshot',
    UNKNOWN: 'unknown',
    PULLING_SNAPSHOT: 'pulling_snapshot',
    ARCHIVED: 'archived',
    ARCHIVING: 'archiving',
    RESIZING: 'resizing',
    SNAPSHOTTING: 'snapshotting',
    FORKING: 'forking',
} as const;

export type SandboxResponseDtoStateEnum = typeof SandboxResponseDtoStateEnum[keyof typeof SandboxResponseDtoStateEnum];
export const SandboxResponseDtoDesiredStateEnum = {
    DESTROYED: 'destroyed',
    STARTED: 'started',
    STOPPED: 'stopped',
    RESIZED: 'resized',
    ARCHIVED: 'archived',
} as const;

export type SandboxResponseDtoDesiredStateEnum = typeof SandboxResponseDtoDesiredStateEnum[keyof typeof SandboxResponseDtoDesiredStateEnum];
export const SandboxResponseDtoClassEnum = {
    SMALL: 'small',
    MEDIUM: 'medium',
    LARGE: 'large',
} as const;

export type SandboxResponseDtoClassEnum = typeof SandboxResponseDtoClassEnum[keyof typeof SandboxResponseDtoClassEnum];
export const SandboxResponseDtoBackupStateEnum = {
    NONE: 'None',
    PENDING: 'Pending',
    IN_PROGRESS: 'InProgress',
    COMPLETED: 'Completed',
    ERROR: 'Error',
} as const;

export type SandboxResponseDtoBackupStateEnum = typeof SandboxResponseDtoBackupStateEnum[keyof typeof SandboxResponseDtoBackupStateEnum];


