/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SandboxSyncDiffEntryDto {
    /**
     * The compared field name
     */
    'field': SandboxSyncDiffEntryDtoFieldEnum;
    /**
     * Normalized DB value as a string; null when the field is unset in the database
     */
    'dbValue'?: string | null;
    /**
     * Normalized OpenSearch value as a string; null when the field is unset in OpenSearch or the document is missing
     */
    'osValue'?: string | null;
    /**
     * Whether the normalized values match
     */
    'status': SandboxSyncDiffEntryDtoStatusEnum;
}

export const SandboxSyncDiffEntryDtoFieldEnum = {
    STATE: 'state',
    DESIRED_STATE: 'desiredState',
    LAST_ACTIVITY_AT: 'lastActivityAt',
    ERROR_REASON: 'errorReason',
    BACKUP_STATE: 'backupState',
} as const;

export type SandboxSyncDiffEntryDtoFieldEnum = typeof SandboxSyncDiffEntryDtoFieldEnum[keyof typeof SandboxSyncDiffEntryDtoFieldEnum];
export const SandboxSyncDiffEntryDtoStatusEnum = {
    MATCH: 'match',
    MISMATCH: 'mismatch',
} as const;

export type SandboxSyncDiffEntryDtoStatusEnum = typeof SandboxSyncDiffEntryDtoStatusEnum[keyof typeof SandboxSyncDiffEntryDtoStatusEnum];


