/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SandboxSyncDiffEntryDto } from './sandbox-sync-diff-entry-dto';

export interface SandboxSyncStatusResponseDto {
    /**
     * Sandbox identifier
     */
    'sandboxId': string;
    /**
     * Owning organization identifier
     */
    'organizationId': string;
    /**
     * Server timestamp when both sides were sampled
     */
    'fetchedAt': string;
    /**
     * Whether OpenSearch returned a document for this sandbox id
     */
    'osDocumentFound': boolean;
    /**
     * True only when every diff entry has status \"match\"
     */
    'inSync': boolean;
    /**
     * Field-by-field comparison
     */
    'diff': Array<SandboxSyncDiffEntryDto>;
    /**
     * Full database row, for the Raw JSON tab
     */
    'db': object;
    /**
     * Raw OpenSearch _source document; null when osDocumentFound is false
     */
    'opensearch'?: object | null;
}

