/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RangeDto } from './range-dto';

export interface SandboxFiltersDto {
    /**
     * Filter by specific sandbox IDs
     */
    'sandboxIds'?: Array<string>;
    /**
     * Filter by organization ID
     */
    'organizationId'?: string;
    /**
     * Search by id (partial match)
     */
    'search'?: string;
    /**
     * Filter by region
     */
    'region'?: string;
    /**
     * Filter by sandbox states
     */
    'state'?: Array<SandboxFiltersDtoStateEnum>;
    /**
     * Exclude specific states
     */
    'excludeStates'?: Array<SandboxFiltersDtoExcludeStatesEnum>;
    /**
     * Filter by runner ID
     */
    'runnerId'?: string;
    /**
     * Filter by public status
     */
    'public'?: boolean;
    /**
     * Only include sandboxes with errors
     */
    'errorOnly'?: boolean;
    /**
     * Filter by has error status
     */
    'hasError'?: boolean;
    /**
     * Filter by CPU range
     */
    'cpu'?: RangeDto;
    /**
     * Filter by memory range
     */
    'memory'?: RangeDto;
    /**
     * Filter by disk range
     */
    'disk'?: RangeDto;
    /**
     * Filter by created after date
     */
    'createdAfter'?: Date;
    /**
     * Filter by created before date
     */
    'createdBefore'?: Date;
}

export const SandboxFiltersDtoStateEnum = {
    CREATING: 'creating',
    RESTORING: 'restoring',
    DESTROYED: 'destroyed',
    DESTROYING: 'destroying',
    STARTED: 'started',
    STOPPED: 'stopped',
    STARTING: 'starting',
    STOPPING: 'stopping',
    ERROR: 'error',
    BUILD_FAILED: 'build_failed',
    PENDING_BUILD: 'pending_build',
    BUILDING_SNAPSHOT: 'building_snapshot',
    UNKNOWN: 'unknown',
    PULLING_SNAPSHOT: 'pulling_snapshot',
    ARCHIVED: 'archived',
    ARCHIVING: 'archiving',
    RESIZING: 'resizing',
    SNAPSHOTTING: 'snapshotting',
    FORKING: 'forking',
} as const;

export type SandboxFiltersDtoStateEnum = typeof SandboxFiltersDtoStateEnum[keyof typeof SandboxFiltersDtoStateEnum];
export const SandboxFiltersDtoExcludeStatesEnum = {
    CREATING: 'creating',
    RESTORING: 'restoring',
    DESTROYED: 'destroyed',
    DESTROYING: 'destroying',
    STARTED: 'started',
    STOPPED: 'stopped',
    STARTING: 'starting',
    STOPPING: 'stopping',
    ERROR: 'error',
    BUILD_FAILED: 'build_failed',
    PENDING_BUILD: 'pending_build',
    BUILDING_SNAPSHOT: 'building_snapshot',
    UNKNOWN: 'unknown',
    PULLING_SNAPSHOT: 'pulling_snapshot',
    ARCHIVED: 'archived',
    ARCHIVING: 'archiving',
    RESIZING: 'resizing',
    SNAPSHOTTING: 'snapshotting',
    FORKING: 'forking',
} as const;

export type SandboxFiltersDtoExcludeStatesEnum = typeof SandboxFiltersDtoExcludeStatesEnum[keyof typeof SandboxFiltersDtoExcludeStatesEnum];


