/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PaginationResponseDto } from './pagination-response-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxSearchDataDto } from './sandbox-search-data-dto'

/**
 *
 * @export
 * @interface SandboxSearchResponseDto
 */
export interface SandboxSearchResponseDto {
  /**
   * Operation success status
   * @type {boolean}
   * @memberof SandboxSearchResponseDto
   */
  success: boolean
  /**
   * Search results data
   * @type {SandboxSearchDataDto}
   * @memberof SandboxSearchResponseDto
   */
  data: SandboxSearchDataDto
  /**
   * Pagination information
   * @type {PaginationResponseDto}
   * @memberof SandboxSearchResponseDto
   */
  pagination: PaginationResponseDto
}
