/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaginationDto } from './pagination-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SortDto } from './sort-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { UserFiltersDto } from './user-filters-dto';

export interface SearchUsersDto {
    /**
     * Filter criteria for users
     */
    'filters'?: UserFiltersDto;
    /**
     * Pagination options
     */
    'pagination'?: PaginationDto;
    /**
     * Sorting options
     */
    'sort'?: SortDto;
}

