/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { PaginationDto } from './pagination-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxFiltersDto } from './sandbox-filters-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { SortDto } from './sort-dto'

/**
 *
 * @export
 * @interface SearchSandboxDto
 */
export interface SearchSandboxDto {
  /**
   * Pagination options
   * @type {PaginationDto}
   * @memberof SearchSandboxDto
   */
  pagination?: PaginationDto
  /**
   * Sort options
   * @type {SortDto}
   * @memberof SearchSandboxDto
   */
  sort?: SortDto
  /**
   * Filter options
   * @type {SandboxFiltersDto}
   * @memberof SearchSandboxDto
   */
  filters?: SandboxFiltersDto
}
