/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SnapshotPropagationStatusDto } from './snapshot-propagation-status-dto';

export interface SnapshotPropagationResponseDto {
    /**
     * Operation success status
     */
    'success': boolean;
    /**
     * Snapshot reference (internal name)
     */
    'snapshotRef': string;
    /**
     * Target region
     */
    'region': string;
    /**
     * Number of eligible runners found
     */
    'eligibleRunners': number;
    /**
     * Number of records inserted (0 if dry run)
     */
    'insertedRecords': number;
    /**
     * Current propagation status by state
     */
    'currentStatus': SnapshotPropagationStatusDto;
    /**
     * Warnings or notices
     */
    'warnings': Array<string>;
}

