/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnapshotResponseDto {
    'id': string;
    'name': string;
    'errorReason'?: string;
    'organizationId': string;
    'imageName': string;
    'state': SnapshotResponseDtoStateEnum;
    'general': boolean;
    'hideFromUsers': boolean;
    'size'?: number;
    'cpu': number;
    'mem': number;
    'disk': number;
    'gpu': number;
    'createdAt': Date;
    'lastUsedAt'?: Date;
}

export const SnapshotResponseDtoStateEnum = {
    BUILDING: 'building',
    PENDING: 'pending',
    PULLING: 'pulling',
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    ERROR: 'error',
    BUILD_FAILED: 'build_failed',
    REMOVING: 'removing',
} as const;

export type SnapshotResponseDtoStateEnum = typeof SnapshotResponseDtoStateEnum[keyof typeof SnapshotResponseDtoStateEnum];


