/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SnapshotPreviewDto
 */
export interface SnapshotPreviewDto {
  /**
   * Snapshot ID
   * @type {string}
   * @memberof SnapshotPreviewDto
   */
  id: string
  /**
   * Snapshot name
   * @type {string}
   * @memberof SnapshotPreviewDto
   */
  name: string
  /**
   * Snapshot state
   * @type {string}
   * @memberof SnapshotPreviewDto
   */
  state: string
}
