/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SnapshotPropagationRequestDto
 */
export interface SnapshotPropagationRequestDto {
  /**
   * Region to propagate snapshot to
   * @type {string}
   * @memberof SnapshotPropagationRequestDto
   */
  region: string
  /**
   * Maximum number of runners to propagate to
   * @type {number}
   * @memberof SnapshotPropagationRequestDto
   */
  maxRunners: number
  /**
   * Dry run mode - validate without inserting
   * @type {boolean}
   * @memberof SnapshotPropagationRequestDto
   */
  dryRun?: boolean
}
