/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SnapshotPropagationStatusDto {
    /**
     * Number of runners with snapshot ready
     */
    'ready': number;
    /**
     * Number of runners currently pulling snapshot
     */
    'pulling_snapshot': number;
    /**
     * Number of runners with failed snapshot pull
     */
    'failed': number;
}

