/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RangeDto } from './range-dto';

export interface SnapshotFiltersDto {
    /**
     * Filter by organization ID
     */
    'organizationId'?: string;
    /**
     * Filter by snapshot name (partial match)
     */
    'name'?: string;
    /**
     * Filter by snapshot state
     */
    'state'?: Array<SnapshotFiltersDtoStateEnum>;
    /**
     * Filter by general snapshots
     */
    'general'?: boolean;
    /**
     * Filter by hide from users status
     */
    'hideFromUsers'?: boolean;
    /**
     * Filter by has error status
     */
    'hasError'?: boolean;
    /**
     * Filter by size range
     */
    'size'?: RangeDto;
    /**
     * Filter by created after date
     */
    'createdAfter'?: Date;
    /**
     * Filter by created before date
     */
    'createdBefore'?: Date;
    /**
     * Filter by last used after date
     */
    'lastUsedAfter'?: Date;
    /**
     * Filter by last used before date
     */
    'lastUsedBefore'?: Date;
}

export const SnapshotFiltersDtoStateEnum = {
    BUILDING: 'building',
    PENDING: 'pending',
    PULLING: 'pulling',
    ACTIVE: 'active',
    INACTIVE: 'inactive',
    ERROR: 'error',
    BUILD_FAILED: 'build_failed',
    REMOVING: 'removing',
} as const;

export type SnapshotFiltersDtoStateEnum = typeof SnapshotFiltersDtoStateEnum[keyof typeof SnapshotFiltersDtoStateEnum];


