/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SortDto
 */
export interface SortDto {
  /**
   * Field to sort by
   * @type {string}
   * @memberof SortDto
   */
  field?: string
  /**
   * Sort order
   * @type {string}
   * @memberof SortDto
   */
  order?: SortDtoOrderEnum
}

export const SortDtoOrderEnum = {
  ASC: 'asc',
  DESC: 'desc',
} as const

export type SortDtoOrderEnum = (typeof SortDtoOrderEnum)[keyof typeof SortDtoOrderEnum]
