/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface SyncStatusDto {
    'state': SyncStatusDtoStateEnum;
    'startedAt': Date | null;
    'finishedAt': Date | null;
    'commit': string | null;
    'error': string | null;
    'hosts': number;
    'added': number;
    'removed': number;
}

export const SyncStatusDtoStateEnum = {
    NEVER_RAN: 'never_ran',
    RUNNING: 'running',
    OK: 'ok',
    ERROR: 'error',
} as const;

export type SyncStatusDtoStateEnum = typeof SyncStatusDtoStateEnum[keyof typeof SyncStatusDtoStateEnum];


