/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateRegionQuotaDto {
    /**
     * Total CPU quota
     */
    'totalCpuQuota'?: number;
    /**
     * Total memory quota in GB
     */
    'totalMemoryQuota'?: number;
    /**
     * Total disk quota in GB
     */
    'totalDiskQuota'?: number;
    /**
     * Max CPU per sandbox in this region. null = use organization default.
     */
    'maxCpuPerSandbox'?: number | null;
    /**
     * Max memory (GB) per sandbox in this region. null = use organization default.
     */
    'maxMemoryPerSandbox'?: number | null;
    /**
     * Max disk (GB) per sandbox in this region. null = use organization default.
     */
    'maxDiskPerSandbox'?: number | null;
    /**
     * Max disk (GB) for non-ephemeral sandboxes. null = fall back to maxDiskPerSandbox. 0 = non-ephemeral sandboxes disabled in this region.
     */
    'maxDiskPerNonEphemeralSandbox'?: number | null;
}

