/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateRegionQuotaDto
 */
export interface UpdateRegionQuotaDto {
  /**
   * Total CPU quota
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  totalCpuQuota?: number
  /**
   * Total memory quota in GB
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  totalMemoryQuota?: number
  /**
   * Total disk quota in GB
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  totalDiskQuota?: number
}
