/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateSettingsDto
 */
export interface UpdateSettingsDto {
  /**
   * Daytona API key for sandbox tools
   * @type {string}
   * @memberof UpdateSettingsDto
   */
  daytonaApiKey?: string
  /**
   * GitHub repository URL for automated PRs
   * @type {string}
   * @memberof UpdateSettingsDto
   */
  githubRepoUrl?: string
  /**
   * GitHub Personal Access Token
   * @type {string}
   * @memberof UpdateSettingsDto
   */
  githubPat?: string
}
