/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateRegionQuotaDto
 */
export interface UpdateRegionQuotaDto {
  /**
   * Total CPU quota
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  totalCpuQuota?: number
  /**
   * Total memory quota in GB
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  totalMemoryQuota?: number
  /**
   * Total disk quota in GB
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  totalDiskQuota?: number
  /**
   * Max CPU per sandbox in this region. null = use organization default.
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  maxCpuPerSandbox?: number | null
  /**
   * Max memory (GB) per sandbox in this region. null = use organization default.
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  maxMemoryPerSandbox?: number | null
  /**
   * Max disk (GB) per sandbox in this region. null = use organization default.
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  maxDiskPerSandbox?: number | null
  /**
   * Max disk (GB) for non-ephemeral sandboxes. null = fall back to maxDiskPerSandbox. 0 = non-ephemeral sandboxes disabled in this region.
   * @type {number}
   * @memberof UpdateRegionQuotaDto
   */
  maxDiskPerNonEphemeralSandbox?: number | null
}
