/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateRunnerDto
 */
export interface UpdateRunnerDto {
  /**
   * Runner state
   * @type {string}
   * @memberof UpdateRunnerDto
   */
  state?: UpdateRunnerDtoStateEnum
  /**
   * Unschedulable flag
   * @type {boolean}
   * @memberof UpdateRunnerDto
   */
  unschedulable?: boolean
  /**
   * Draining flag
   * @type {boolean}
   * @memberof UpdateRunnerDto
   */
  draining?: boolean
  /**
   * Runner region
   * @type {string}
   * @memberof UpdateRunnerDto
   */
  region?: string
  /**
   * CPU cores
   * @type {number}
   * @memberof UpdateRunnerDto
   */
  cpu?: number
  /**
   * Memory in GiB
   * @type {number}
   * @memberof UpdateRunnerDto
   */
  memoryGiB?: number
  /**
   * Disk in GiB
   * @type {number}
   * @memberof UpdateRunnerDto
   */
  diskGiB?: number
}

export const UpdateRunnerDtoStateEnum = {
  INITIALIZING: 'initializing',
  READY: 'ready',
  DISABLED: 'disabled',
  DECOMMISSIONED: 'decommissioned',
  UNRESPONSIVE: 'unresponsive',
} as const

export type UpdateRunnerDtoStateEnum = (typeof UpdateRunnerDtoStateEnum)[keyof typeof UpdateRunnerDtoStateEnum]
