/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateOrganizationDto {
    /**
     * Organization name
     */
    'name'?: string;
    /**
     * Is organization suspended
     */
    'suspended'?: boolean;
    /**
     * Suspension end date
     */
    'suspendedUntil'?: Date;
    /**
     * Default region ID
     */
    'defaultRegionId'?: string;
    /**
     * Telemetry enabled
     */
    'telemetryEnabled'?: boolean;
    /**
     * Max CPU per sandbox
     */
    'maxCpuPerSandbox'?: number;
    /**
     * Max memory per sandbox in GB
     */
    'maxMemoryPerSandbox'?: number;
    /**
     * Max disk per sandbox in GB
     */
    'maxDiskPerSandbox'?: number;
    /**
     * Max snapshot size in GB
     */
    'maxSnapshotSize'?: number;
    /**
     * Snapshot quota in GB
     */
    'snapshotQuota'?: number;
    /**
     * Volume quota in GB
     */
    'volumeQuota'?: number;
    /**
     * Limit network egress for sandboxes
     */
    'sandboxLimitedNetworkEgress'?: boolean;
    /**
     * Snapshot deactivation timeout in minutes (default 20160 = 14 days). Min 1.
     */
    'snapshotDeactivationTimeoutMinutes'?: number;
    /**
     * Authenticated request rate limit (requests per TTL window). null = use global default.
     */
    'authenticatedRateLimit'?: number | null;
    /**
     * Sandbox create rate limit. null = use global default.
     */
    'sandboxCreateRateLimit'?: number | null;
    /**
     * Sandbox lifecycle (start/stop/etc) rate limit. null = use global default.
     */
    'sandboxLifecycleRateLimit'?: number | null;
    /**
     * TTL window (seconds) for authenticatedRateLimit. null = use global default.
     */
    'authenticatedRateLimitTtlSeconds'?: number | null;
    /**
     * TTL window (seconds) for sandboxCreateRateLimit. null = use global default.
     */
    'sandboxCreateRateLimitTtlSeconds'?: number | null;
    /**
     * TTL window (seconds) for sandboxLifecycleRateLimit. null = use global default.
     */
    'sandboxLifecycleRateLimitTtlSeconds'?: number | null;
}

