/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateQuotaRequestDto {
    /**
     * Organization ID (UUID)
     */
    'organizationId': string;
    /**
     * Region ID (e.g. \"us\", \"eu\")
     */
    'regionId': string;
    /**
     * Sandbox class of the quota to update. Defaults to \"container\".
     */
    'sandboxClass'?: UpdateQuotaRequestDtoSandboxClassEnum;
    /**
     * CPU cores to add to totalCpuQuota
     */
    'cpuDelta'?: number;
    /**
     * Memory (GiB) to add to totalMemoryQuota
     */
    'memoryDelta'?: number;
    /**
     * Disk (GiB) to add to totalDiskQuota
     */
    'diskDelta'?: number;
    /**
     * GPUs to add to totalGpuQuota
     */
    'gpuDelta'?: number;
    /**
     * Why this update is needed (shown to approvers)
     */
    'reason'?: string;
}

export const UpdateQuotaRequestDtoSandboxClassEnum = {
    LINUX_VM: 'linux-vm',
    CONTAINER: 'container',
    ANDROID: 'android',
    WINDOWS: 'windows',
} as const;

export type UpdateQuotaRequestDtoSandboxClassEnum = typeof UpdateQuotaRequestDtoSandboxClassEnum[keyof typeof UpdateQuotaRequestDtoSandboxClassEnum];


