/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateSandboxDto {
    /**
     * Sandbox state
     */
    'state'?: UpdateSandboxDtoStateEnum;
    /**
     * Desired sandbox state
     */
    'desiredState'?: UpdateSandboxDtoDesiredStateEnum;
    /**
     * Runner ID
     */
    'runnerId'?: string;
    /**
     * Error reason
     */
    'errorReason'?: string;
    /**
     * Block all network traffic
     */
    'networkBlockAll'?: boolean;
    /**
     * Network allow list
     */
    'networkAllowList'?: string;
    /**
     * Labels (key-value pairs)
     */
    'labels'?: object;
    /**
     * Backup state
     */
    'backupState'?: UpdateSandboxDtoBackupStateEnum;
    /**
     * Backup error reason
     */
    'backupErrorReason'?: string;
    /**
     * Auto-stop interval in minutes
     */
    'autoStopInterval'?: number;
    /**
     * Auto-archive interval in minutes
     */
    'autoArchiveInterval'?: number;
    /**
     * Auto-delete interval in minutes
     */
    'autoDeleteInterval'?: number;
    /**
     * Is pending
     */
    'pending'?: boolean;
    /**
     * Authentication token
     */
    'authToken'?: string;
    /**
     * CPU cores
     */
    'cpu'?: number;
    /**
     * Memory in GiB
     */
    'mem'?: number;
    /**
     * Disk in GiB
     */
    'disk'?: number;
    /**
     * Is public
     */
    'public'?: boolean;
    /**
     * Is recoverable
     */
    'recoverable'?: boolean;
}

export const UpdateSandboxDtoStateEnum = {
    CREATING: 'creating',
    RESTORING: 'restoring',
    DESTROYED: 'destroyed',
    DESTROYING: 'destroying',
    STARTED: 'started',
    STOPPED: 'stopped',
    STARTING: 'starting',
    STOPPING: 'stopping',
    ERROR: 'error',
    BUILD_FAILED: 'build_failed',
    PENDING_BUILD: 'pending_build',
    BUILDING_SNAPSHOT: 'building_snapshot',
    UNKNOWN: 'unknown',
    PULLING_SNAPSHOT: 'pulling_snapshot',
    ARCHIVED: 'archived',
    ARCHIVING: 'archiving',
    RESIZING: 'resizing',
    SNAPSHOTTING: 'snapshotting',
    FORKING: 'forking',
} as const;

export type UpdateSandboxDtoStateEnum = typeof UpdateSandboxDtoStateEnum[keyof typeof UpdateSandboxDtoStateEnum];
export const UpdateSandboxDtoDesiredStateEnum = {
    DESTROYED: 'destroyed',
    STARTED: 'started',
    STOPPED: 'stopped',
    RESIZED: 'resized',
    ARCHIVED: 'archived',
} as const;

export type UpdateSandboxDtoDesiredStateEnum = typeof UpdateSandboxDtoDesiredStateEnum[keyof typeof UpdateSandboxDtoDesiredStateEnum];
export const UpdateSandboxDtoBackupStateEnum = {
    NONE: 'None',
    PENDING: 'Pending',
    IN_PROGRESS: 'InProgress',
    COMPLETED: 'Completed',
    ERROR: 'Error',
} as const;

export type UpdateSandboxDtoBackupStateEnum = typeof UpdateSandboxDtoBackupStateEnum[keyof typeof UpdateSandboxDtoBackupStateEnum];


