/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateRunnerDto {
    /**
     * Runner state
     */
    'state'?: UpdateRunnerDtoStateEnum;
    /**
     * Unschedulable flag
     */
    'unschedulable'?: boolean;
    /**
     * Draining flag
     */
    'draining'?: boolean;
    /**
     * Runner region
     */
    'region'?: string;
    /**
     * CPU cores
     */
    'cpu'?: number;
    /**
     * Memory in GiB
     */
    'memoryGiB'?: number;
    /**
     * Disk in GiB
     */
    'diskGiB'?: number;
}

export const UpdateRunnerDtoStateEnum = {
    INITIALIZING: 'initializing',
    READY: 'ready',
    DISABLED: 'disabled',
    DECOMMISSIONED: 'decommissioned',
    UNRESPONSIVE: 'unresponsive',
} as const;

export type UpdateRunnerDtoStateEnum = typeof UpdateRunnerDtoStateEnum[keyof typeof UpdateRunnerDtoStateEnum];


