/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateSnapshotDto
 */
export interface UpdateSnapshotDto {
  /**
   * Snapshot name
   * @type {string}
   * @memberof UpdateSnapshotDto
   */
  name?: string
  /**
   * Hide from users
   * @type {boolean}
   * @memberof UpdateSnapshotDto
   */
  hideFromUsers?: boolean
  /**
   * General snapshot (available to all)
   * @type {boolean}
   * @memberof UpdateSnapshotDto
   */
  general?: boolean
}
