/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserFiltersDto
 */
export interface UserFiltersDto {
  /**
   * Search by email or user ID (partial match)
   * @type {string}
   * @memberof UserFiltersDto
   */
  search?: string
  /**
   * Filter by user email (partial match)
   * @type {string}
   * @memberof UserFiltersDto
   */
  email?: string
  /**
   * Filter by user name (partial match)
   * @type {string}
   * @memberof UserFiltersDto
   */
  name?: string
  /**
   * Filter by user ID
   * @type {string}
   * @memberof UserFiltersDto
   */
  userId?: string
  /**
   * Filter by email verified status
   * @type {boolean}
   * @memberof UserFiltersDto
   */
  emailVerified?: boolean
  /**
   * Created after date (ISO 8601)
   * @type {string}
   * @memberof UserFiltersDto
   */
  createdAfter?: string
  /**
   * Created before date (ISO 8601)
   * @type {string}
   * @memberof UserFiltersDto
   */
  createdBefore?: string
}
