/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserResponseDto {
    /**
     * User ID
     */
    'id': string;
    /**
     * User name
     */
    'name': string;
    /**
     * User email
     */
    'email': string;
    /**
     * Email verified status
     */
    'emailVerified': boolean;
    /**
     * Created at
     */
    'createdAt': Date;
    /**
     * Number of organizations user owns
     */
    'organizationsCount'?: number;
}

