/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrganizationPreviewDto } from './organization-preview-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SandboxPreviewDto } from './sandbox-preview-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SnapshotPreviewDto } from './snapshot-preview-dto';

export interface UserDeletionPreviewDto {
    /**
     * User ID
     */
    'userId': string;
    /**
     * User email
     */
    'email': string;
    /**
     * User name
     */
    'name': string;
    /**
     * Organizations where user is owner
     */
    'organizations': Array<OrganizationPreviewDto>;
    /**
     * Sandboxes in owned organizations
     */
    'sandboxes': Array<SandboxPreviewDto>;
    /**
     * Snapshots in owned organizations
     */
    'snapshots': Array<SnapshotPreviewDto>;
    /**
     * Number of API keys in owned organizations
     */
    'apiKeys': number;
    /**
     * Number of sandbox templates in owned organizations
     */
    'sandboxTemplates': number;
    /**
     * Estimated impact description
     */
    'estimatedImpact': string;
}

