/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { ExecutedActionsDto } from './executed-actions-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { ManualStepDto } from './manual-step-dto'

/**
 *
 * @export
 * @interface UserDeletionResponseDto
 */
export interface UserDeletionResponseDto {
  /**
   * Operation success status
   * @type {boolean}
   * @memberof UserDeletionResponseDto
   */
  success: boolean
  /**
   * Actions executed by the service
   * @type {ExecutedActionsDto}
   * @memberof UserDeletionResponseDto
   */
  executedActions: ExecutedActionsDto
  /**
   * Manual steps required in external services
   * @type {Array<ManualStepDto>}
   * @memberof UserDeletionResponseDto
   */
  manualSteps: Array<ManualStepDto>
  /**
   * Warnings or notices
   * @type {Array<string>}
   * @memberof UserDeletionResponseDto
   */
  warnings: Array<string>
}
