/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UserFiltersDto {
    /**
     * Search by email or user ID (partial match)
     */
    'search'?: string;
    /**
     * Filter by user email (partial match)
     */
    'email'?: string;
    /**
     * Filter by user name (partial match)
     */
    'name'?: string;
    /**
     * Filter by user ID
     */
    'userId'?: string;
    /**
     * Filter by email verified status
     */
    'emailVerified'?: boolean;
    /**
     * Created after date (ISO 8601)
     */
    'createdAfter'?: string;
    /**
     * Created before date (ISO 8601)
     */
    'createdBefore'?: string;
}

