/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UserDeletionOptionsDto
 */
export interface UserDeletionOptionsDto {
  /**
   * Delete sandbox templates (hard delete)
   * @type {boolean}
   * @memberof UserDeletionOptionsDto
   */
  deleteSandboxTemplates?: boolean
  /**
   * Delete API keys (hard delete)
   * @type {boolean}
   * @memberof UserDeletionOptionsDto
   */
  deleteApiKeys?: boolean
  /**
   * Delete organization memberships (hard delete)
   * @type {boolean}
   * @memberof UserDeletionOptionsDto
   */
  deleteOrgMemberships?: boolean
}
