replicaCount: 1

image:
  repository: ghcr.io/daytonaio/daytona-docs
  tag: "latest"
  pullPolicy: Always

imagePullSecrets:
  - name: daytonabot-token

podAnnotations: {}

containerPort: 4321

env:
  FUNCTIONS_PORT: "4321"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  host: ""
  annotations: {}
  tls:
    enabled: true
    secretName: docs-stage-tls
  basicAuth:
    enabled: true
    secretName: docs-preview-basic-auth
    realm: "Docs Preview"

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
