// Minimal client stubs for sysbox-mgr's gRPC API (unix:///run/sysbox/sysmgr.sock).
//
// Mirrors nestybox/sysbox-ipc sysboxMgrGrpc/sysboxMgrProtobuf/sysboxMgrProtobuf.proto,
// which is not consumable as a Go module (generated code is not checked in upstream and
// its deps only resolve inside the sysbox workspace). The proto package and service name
// must match upstream exactly — they form the gRPC method path.
//
// Regenerate: protoc --go_out=. --go_opt=paths=source_relative \
//   --go-grpc_out=. --go-grpc_opt=paths=source_relative sysboxmgr.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: sysboxmgr.proto

package sysboxmgr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysboxMgrStateChannel_Unregister_FullMethodName = "/protobuf.sysboxMgrStateChannel/Unregister"
)

// SysboxMgrStateChannelClient is the client API for SysboxMgrStateChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysboxMgrStateChannelClient interface {
	Unregister(ctx context.Context, in *UnregisterReq, opts ...grpc.CallOption) (*UnregisterResp, error)
}

type sysboxMgrStateChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewSysboxMgrStateChannelClient(cc grpc.ClientConnInterface) SysboxMgrStateChannelClient {
	return &sysboxMgrStateChannelClient{cc}
}

func (c *sysboxMgrStateChannelClient) Unregister(ctx context.Context, in *UnregisterReq, opts ...grpc.CallOption) (*UnregisterResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterResp)
	err := c.cc.Invoke(ctx, SysboxMgrStateChannel_Unregister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysboxMgrStateChannelServer is the server API for SysboxMgrStateChannel service.
// All implementations must embed UnimplementedSysboxMgrStateChannelServer
// for forward compatibility.
type SysboxMgrStateChannelServer interface {
	Unregister(context.Context, *UnregisterReq) (*UnregisterResp, error)
	mustEmbedUnimplementedSysboxMgrStateChannelServer()
}

// UnimplementedSysboxMgrStateChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysboxMgrStateChannelServer struct{}

func (UnimplementedSysboxMgrStateChannelServer) Unregister(context.Context, *UnregisterReq) (*UnregisterResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedSysboxMgrStateChannelServer) mustEmbedUnimplementedSysboxMgrStateChannelServer() {}
func (UnimplementedSysboxMgrStateChannelServer) testEmbeddedByValue()                               {}

// UnsafeSysboxMgrStateChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysboxMgrStateChannelServer will
// result in compilation errors.
type UnsafeSysboxMgrStateChannelServer interface {
	mustEmbedUnimplementedSysboxMgrStateChannelServer()
}

func RegisterSysboxMgrStateChannelServer(s grpc.ServiceRegistrar, srv SysboxMgrStateChannelServer) {
	// If the following call panics, it indicates UnimplementedSysboxMgrStateChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysboxMgrStateChannel_ServiceDesc, srv)
}

func _SysboxMgrStateChannel_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysboxMgrStateChannelServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysboxMgrStateChannel_Unregister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysboxMgrStateChannelServer).Unregister(ctx, req.(*UnregisterReq))
	}
	return interceptor(ctx, in, info, handler)
}

// SysboxMgrStateChannel_ServiceDesc is the grpc.ServiceDesc for SysboxMgrStateChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysboxMgrStateChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.sysboxMgrStateChannel",
	HandlerType: (*SysboxMgrStateChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unregister",
			Handler:    _SysboxMgrStateChannel_Unregister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sysboxmgr.proto",
}
