export enum AuditAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  SEARCH = 'search',
  BULK_INSERT = 'bulk_insert',
  BULK_UPDATE = 'bulk_update',
  BULK_DELETE = 'bulk_delete',
  PROPAGATE = 'propagate',
  DELETION_PREVIEW = 'deletion_preview',
  IMPORT = 'import',
  LOGIN = 'login',
  FORCE_RESYNC = 'force_resync',
  QUOTA_BUMP_CREATE = 'quota_bump_create',
  QUOTA_BUMP_APPROVE = 'quota_bump_approve',
  QUOTA_BUMP_REJECT = 'quota_bump_reject',
  QUOTA_BUMP_CANCEL = 'quota_bump_cancel',
  QUOTA_BUMP_EXPIRE = 'quota_bump_expire',
}
