export enum AuditAction {
  CREATE = 'create',
  READ = 'read',
  UPDATE = 'update',
  DELETE = 'delete',
  SEARCH = 'search',
  BULK_INSERT = 'bulk_insert',
  BULK_UPDATE = 'bulk_update',
  BULK_DELETE = 'bulk_delete',
  PROPAGATE = 'propagate',
  DELETION_PREVIEW = 'deletion_preview',
  IMPORT = 'import',
  LOGIN = 'login',
  FORCE_RESYNC = 'force_resync',
  QUOTA_REQUEST_UPDATE = 'quota_request_update',
  QUOTA_REQUEST_CREATE = 'quota_request_create',
  QUOTA_REQUEST_APPROVE = 'quota_request_approve',
  QUOTA_REQUEST_REJECT = 'quota_request_reject',
  QUOTA_REQUEST_CANCEL = 'quota_request_cancel',
  QUOTA_REQUEST_EXPIRE = 'quota_request_expire',
}
