/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AddMaintenanceNoteDto } from '../models';
// @ts-ignore
import type { CreateMaintenanceRequestDto } from '../models';
// @ts-ignore
import type { DiscrepancyDto } from '../models';
// @ts-ignore
import type { FleetFilterOptionsDto } from '../models';
// @ts-ignore
import type { FleetRunnerDetailDto } from '../models';
// @ts-ignore
import type { FleetRunnerSearchResponseDto } from '../models';
// @ts-ignore
import type { IncomingMaintenanceRequestsResponseDto } from '../models';
// @ts-ignore
import type { MaintenanceRequestDetailDto } from '../models';
// @ts-ignore
import type { MaintenanceRequestDto } from '../models';
// @ts-ignore
import type { RunnerEventDto } from '../models';
// @ts-ignore
import type { SearchFleetRunnersDto } from '../models';
// @ts-ignore
import type { SyncStatusDto } from '../models';
// @ts-ignore
import type { TransitionMaintenanceRequestDto } from '../models';
// @ts-ignore
import type { UpdateMaintenanceRequestDto } from '../models';
/**
 * FleetApi - axios parameter creator
 */
export const FleetApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Fleet runner detail with production state, requests and event timeline
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetRunnersControllerDetail: async (name: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('fleetRunnersControllerDetail', 'name', name)
            const localVarPath = `/fleet/runners/{name}`
                .replace(`{${"name"}}`, encodeURIComponent(String(name)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Where inventory and production disagree
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetRunnersControllerDiscrepancies: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/fleet/runners/discrepancies`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Distinct values for the fleet filter dropdowns
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetRunnersControllerFilterOptions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/fleet/runners/filter-options`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search fleet runners (inventory merged with live production state)
         * @param {SearchFleetRunnersDto} searchFleetRunnersDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetRunnersControllerSearch: async (searchFleetRunnersDto: SearchFleetRunnersDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchFleetRunnersDto' is not null or undefined
            assertParamExists('fleetRunnersControllerSearch', 'searchFleetRunnersDto', searchFleetRunnersDto)
            const localVarPath = `/fleet/runners/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchFleetRunnersDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Current inventory sync status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetSyncControllerStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/fleet/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Trigger an inventory sync now
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetSyncControllerTrigger: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/fleet/sync`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Add a note to the request timeline
         * @param {string} id 
         * @param {AddMaintenanceNoteDto} addMaintenanceNoteDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerAddNote: async (id: string, addMaintenanceNoteDto: AddMaintenanceNoteDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('maintenanceRequestsControllerAddNote', 'id', id)
            // verify required parameter 'addMaintenanceNoteDto' is not null or undefined
            assertParamExists('maintenanceRequestsControllerAddNote', 'addMaintenanceNoteDto', addMaintenanceNoteDto)
            const localVarPath = `/fleet/maintenance-requests/{id}/notes`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addMaintenanceNoteDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary File a maintenance request
         * @param {CreateMaintenanceRequestDto} createMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerCreate: async (createMaintenanceRequestDto: CreateMaintenanceRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createMaintenanceRequestDto' is not null or undefined
            assertParamExists('maintenanceRequestsControllerCreate', 'createMaintenanceRequestDto', createMaintenanceRequestDto)
            const localVarPath = `/fleet/maintenance-requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMaintenanceRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Request detail with live drain progress and event timeline
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerDetail: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('maintenanceRequestsControllerDetail', 'id', id)
            const localVarPath = `/fleet/maintenance-requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Incoming (not yet acknowledged) maintenance requests — notifications feed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerIncoming: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/fleet/maintenance-requests/incoming`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Transition the request to a new status
         * @param {string} id 
         * @param {TransitionMaintenanceRequestDto} transitionMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerTransition: async (id: string, transitionMaintenanceRequestDto: TransitionMaintenanceRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('maintenanceRequestsControllerTransition', 'id', id)
            // verify required parameter 'transitionMaintenanceRequestDto' is not null or undefined
            assertParamExists('maintenanceRequestsControllerTransition', 'transitionMaintenanceRequestDto', transitionMaintenanceRequestDto)
            const localVarPath = `/fleet/maintenance-requests/{id}/status`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transitionMaintenanceRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update request title/description/due date/Slack link
         * @param {string} id 
         * @param {UpdateMaintenanceRequestDto} updateMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerUpdate: async (id: string, updateMaintenanceRequestDto: UpdateMaintenanceRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('maintenanceRequestsControllerUpdate', 'id', id)
            // verify required parameter 'updateMaintenanceRequestDto' is not null or undefined
            assertParamExists('maintenanceRequestsControllerUpdate', 'updateMaintenanceRequestDto', updateMaintenanceRequestDto)
            const localVarPath = `/fleet/maintenance-requests/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateMaintenanceRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FleetApi - functional programming interface
 */
export const FleetApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FleetApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Fleet runner detail with production state, requests and event timeline
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fleetRunnersControllerDetail(name: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FleetRunnerDetailDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fleetRunnersControllerDetail(name, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.fleetRunnersControllerDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Where inventory and production disagree
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fleetRunnersControllerDiscrepancies(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<DiscrepancyDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fleetRunnersControllerDiscrepancies(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.fleetRunnersControllerDiscrepancies']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Distinct values for the fleet filter dropdowns
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fleetRunnersControllerFilterOptions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FleetFilterOptionsDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fleetRunnersControllerFilterOptions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.fleetRunnersControllerFilterOptions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search fleet runners (inventory merged with live production state)
         * @param {SearchFleetRunnersDto} searchFleetRunnersDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fleetRunnersControllerSearch(searchFleetRunnersDto: SearchFleetRunnersDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FleetRunnerSearchResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fleetRunnersControllerSearch(searchFleetRunnersDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.fleetRunnersControllerSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Current inventory sync status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fleetSyncControllerStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SyncStatusDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fleetSyncControllerStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.fleetSyncControllerStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Trigger an inventory sync now
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fleetSyncControllerTrigger(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SyncStatusDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fleetSyncControllerTrigger(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.fleetSyncControllerTrigger']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Add a note to the request timeline
         * @param {string} id 
         * @param {AddMaintenanceNoteDto} addMaintenanceNoteDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async maintenanceRequestsControllerAddNote(id: string, addMaintenanceNoteDto: AddMaintenanceNoteDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RunnerEventDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.maintenanceRequestsControllerAddNote(id, addMaintenanceNoteDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.maintenanceRequestsControllerAddNote']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary File a maintenance request
         * @param {CreateMaintenanceRequestDto} createMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async maintenanceRequestsControllerCreate(createMaintenanceRequestDto: CreateMaintenanceRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaintenanceRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.maintenanceRequestsControllerCreate(createMaintenanceRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.maintenanceRequestsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Request detail with live drain progress and event timeline
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async maintenanceRequestsControllerDetail(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaintenanceRequestDetailDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.maintenanceRequestsControllerDetail(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.maintenanceRequestsControllerDetail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Incoming (not yet acknowledged) maintenance requests — notifications feed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async maintenanceRequestsControllerIncoming(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IncomingMaintenanceRequestsResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.maintenanceRequestsControllerIncoming(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.maintenanceRequestsControllerIncoming']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Transition the request to a new status
         * @param {string} id 
         * @param {TransitionMaintenanceRequestDto} transitionMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async maintenanceRequestsControllerTransition(id: string, transitionMaintenanceRequestDto: TransitionMaintenanceRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaintenanceRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.maintenanceRequestsControllerTransition(id, transitionMaintenanceRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.maintenanceRequestsControllerTransition']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update request title/description/due date/Slack link
         * @param {string} id 
         * @param {UpdateMaintenanceRequestDto} updateMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async maintenanceRequestsControllerUpdate(id: string, updateMaintenanceRequestDto: UpdateMaintenanceRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MaintenanceRequestDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.maintenanceRequestsControllerUpdate(id, updateMaintenanceRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FleetApi.maintenanceRequestsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FleetApi - factory interface
 */
export const FleetApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FleetApiFp(configuration)
    return {
        /**
         * 
         * @summary Fleet runner detail with production state, requests and event timeline
         * @param {string} name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetRunnersControllerDetail(name: string, options?: RawAxiosRequestConfig): AxiosPromise<FleetRunnerDetailDto> {
            return localVarFp.fleetRunnersControllerDetail(name, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Where inventory and production disagree
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetRunnersControllerDiscrepancies(options?: RawAxiosRequestConfig): AxiosPromise<Array<DiscrepancyDto>> {
            return localVarFp.fleetRunnersControllerDiscrepancies(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Distinct values for the fleet filter dropdowns
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetRunnersControllerFilterOptions(options?: RawAxiosRequestConfig): AxiosPromise<FleetFilterOptionsDto> {
            return localVarFp.fleetRunnersControllerFilterOptions(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search fleet runners (inventory merged with live production state)
         * @param {SearchFleetRunnersDto} searchFleetRunnersDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetRunnersControllerSearch(searchFleetRunnersDto: SearchFleetRunnersDto, options?: RawAxiosRequestConfig): AxiosPromise<FleetRunnerSearchResponseDto> {
            return localVarFp.fleetRunnersControllerSearch(searchFleetRunnersDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Current inventory sync status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetSyncControllerStatus(options?: RawAxiosRequestConfig): AxiosPromise<SyncStatusDto> {
            return localVarFp.fleetSyncControllerStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Trigger an inventory sync now
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fleetSyncControllerTrigger(options?: RawAxiosRequestConfig): AxiosPromise<SyncStatusDto> {
            return localVarFp.fleetSyncControllerTrigger(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Add a note to the request timeline
         * @param {string} id 
         * @param {AddMaintenanceNoteDto} addMaintenanceNoteDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerAddNote(id: string, addMaintenanceNoteDto: AddMaintenanceNoteDto, options?: RawAxiosRequestConfig): AxiosPromise<RunnerEventDto> {
            return localVarFp.maintenanceRequestsControllerAddNote(id, addMaintenanceNoteDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary File a maintenance request
         * @param {CreateMaintenanceRequestDto} createMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerCreate(createMaintenanceRequestDto: CreateMaintenanceRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<MaintenanceRequestDto> {
            return localVarFp.maintenanceRequestsControllerCreate(createMaintenanceRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Request detail with live drain progress and event timeline
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerDetail(id: string, options?: RawAxiosRequestConfig): AxiosPromise<MaintenanceRequestDetailDto> {
            return localVarFp.maintenanceRequestsControllerDetail(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Incoming (not yet acknowledged) maintenance requests — notifications feed
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerIncoming(options?: RawAxiosRequestConfig): AxiosPromise<IncomingMaintenanceRequestsResponseDto> {
            return localVarFp.maintenanceRequestsControllerIncoming(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Transition the request to a new status
         * @param {string} id 
         * @param {TransitionMaintenanceRequestDto} transitionMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerTransition(id: string, transitionMaintenanceRequestDto: TransitionMaintenanceRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<MaintenanceRequestDto> {
            return localVarFp.maintenanceRequestsControllerTransition(id, transitionMaintenanceRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update request title/description/due date/Slack link
         * @param {string} id 
         * @param {UpdateMaintenanceRequestDto} updateMaintenanceRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        maintenanceRequestsControllerUpdate(id: string, updateMaintenanceRequestDto: UpdateMaintenanceRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<MaintenanceRequestDto> {
            return localVarFp.maintenanceRequestsControllerUpdate(id, updateMaintenanceRequestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FleetApi - object-oriented interface
 */
export class FleetApi extends BaseAPI {
    /**
     * 
     * @summary Fleet runner detail with production state, requests and event timeline
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fleetRunnersControllerDetail(name: string, options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).fleetRunnersControllerDetail(name, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Where inventory and production disagree
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fleetRunnersControllerDiscrepancies(options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).fleetRunnersControllerDiscrepancies(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Distinct values for the fleet filter dropdowns
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fleetRunnersControllerFilterOptions(options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).fleetRunnersControllerFilterOptions(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search fleet runners (inventory merged with live production state)
     * @param {SearchFleetRunnersDto} searchFleetRunnersDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fleetRunnersControllerSearch(searchFleetRunnersDto: SearchFleetRunnersDto, options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).fleetRunnersControllerSearch(searchFleetRunnersDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Current inventory sync status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fleetSyncControllerStatus(options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).fleetSyncControllerStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Trigger an inventory sync now
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fleetSyncControllerTrigger(options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).fleetSyncControllerTrigger(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Add a note to the request timeline
     * @param {string} id 
     * @param {AddMaintenanceNoteDto} addMaintenanceNoteDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public maintenanceRequestsControllerAddNote(id: string, addMaintenanceNoteDto: AddMaintenanceNoteDto, options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).maintenanceRequestsControllerAddNote(id, addMaintenanceNoteDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary File a maintenance request
     * @param {CreateMaintenanceRequestDto} createMaintenanceRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public maintenanceRequestsControllerCreate(createMaintenanceRequestDto: CreateMaintenanceRequestDto, options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).maintenanceRequestsControllerCreate(createMaintenanceRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Request detail with live drain progress and event timeline
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public maintenanceRequestsControllerDetail(id: string, options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).maintenanceRequestsControllerDetail(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Incoming (not yet acknowledged) maintenance requests — notifications feed
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public maintenanceRequestsControllerIncoming(options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).maintenanceRequestsControllerIncoming(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Transition the request to a new status
     * @param {string} id 
     * @param {TransitionMaintenanceRequestDto} transitionMaintenanceRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public maintenanceRequestsControllerTransition(id: string, transitionMaintenanceRequestDto: TransitionMaintenanceRequestDto, options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).maintenanceRequestsControllerTransition(id, transitionMaintenanceRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update request title/description/due date/Slack link
     * @param {string} id 
     * @param {UpdateMaintenanceRequestDto} updateMaintenanceRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public maintenanceRequestsControllerUpdate(id: string, updateMaintenanceRequestDto: UpdateMaintenanceRequestDto, options?: RawAxiosRequestConfig) {
        return FleetApiFp(this.configuration).maintenanceRequestsControllerUpdate(id, updateMaintenanceRequestDto, options).then((request) => request(this.axios, this.basePath));
    }
}

