/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BulkUpdateRegionQuotaDto } from '../models';
// @ts-ignore
import type { BulkUpdateResponseDto } from '../models';
// @ts-ignore
import type { CreateQuotaRequestDto } from '../models';
// @ts-ignore
import type { CreateRegionQuotaDto } from '../models';
// @ts-ignore
import type { PatchRegionQuotaDto } from '../models';
// @ts-ignore
import type { RegionQuotaSearchResponseDto } from '../models';
// @ts-ignore
import type { RejectQuotaRequestDto } from '../models';
// @ts-ignore
import type { SearchRegionQuotaDto } from '../models';
// @ts-ignore
import type { UpdateQuotaRequestDto } from '../models';
/**
 * RegionQuotasApi - axios parameter creator
 */
export const RegionQuotasApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Approve a pending request (make it permanent)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerApprove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quotaRequestsControllerApprove', 'id', id)
            const localVarPath = `/region-quotas/requests/{id}/approve`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the current editor\'s remaining daily update budget
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerBudget: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/region-quotas/requests/budget`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Cancel your own pending request and revert the quota
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerCancel: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quotaRequestsControllerCancel', 'id', id)
            const localVarPath = `/region-quotas/requests/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the default limits a create request grants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerCreateDefaults: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/region-quotas/requests/create-defaults`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List pending quota requests awaiting approval
         * @param {number} [page] Page number (1-indexed)
         * @param {number} [pageSize] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerListPending: async (page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/region-quotas/requests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['pageSize'] = pageSize;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Reject a pending request and revert the quota
         * @param {string} id 
         * @param {RejectQuotaRequestDto} rejectQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerReject: async (id: string, rejectQuotaRequestDto: RejectQuotaRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('quotaRequestsControllerReject', 'id', id)
            // verify required parameter 'rejectQuotaRequestDto' is not null or undefined
            assertParamExists('quotaRequestsControllerReject', 'rejectQuotaRequestDto', rejectQuotaRequestDto)
            const localVarPath = `/region-quotas/requests/{id}/reject`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rejectQuotaRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a region quota with the default limits (pending approval)
         * @param {CreateQuotaRequestDto} createQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerRequestCreate: async (createQuotaRequestDto: CreateQuotaRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createQuotaRequestDto' is not null or undefined
            assertParamExists('quotaRequestsControllerRequestCreate', 'createQuotaRequestDto', createQuotaRequestDto)
            const localVarPath = `/region-quotas/requests/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createQuotaRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Request a temporary region quota update (increase)
         * @param {UpdateQuotaRequestDto} updateQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerRequestUpdate: async (updateQuotaRequestDto: UpdateQuotaRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateQuotaRequestDto' is not null or undefined
            assertParamExists('quotaRequestsControllerRequestUpdate', 'updateQuotaRequestDto', updateQuotaRequestDto)
            const localVarPath = `/region-quotas/requests/update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateQuotaRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Bulk update region-quotas
         * @param {BulkUpdateRegionQuotaDto} bulkUpdateRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasBulkControllerBulkUpdate: async (bulkUpdateRegionQuotaDto: BulkUpdateRegionQuotaDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkUpdateRegionQuotaDto' is not null or undefined
            assertParamExists('regionQuotasBulkControllerBulkUpdate', 'bulkUpdateRegionQuotaDto', bulkUpdateRegionQuotaDto)
            const localVarPath = `/region-quotas/bulk-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkUpdateRegionQuotaDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a region quota
         * @param {CreateRegionQuotaDto} createRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasControllerCreate: async (createRegionQuotaDto: CreateRegionQuotaDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createRegionQuotaDto' is not null or undefined
            assertParamExists('regionQuotasControllerCreate', 'createRegionQuotaDto', createRegionQuotaDto)
            const localVarPath = `/region-quotas`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createRegionQuotaDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List regions a quota can target
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasControllerListRegions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/region-quotas/regions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a region quota
         * @param {string} organizationId Organization ID
         * @param {string} region Region ID
         * @param {PatchRegionQuotaDto} patchRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasControllerUpdate: async (organizationId: string, region: string, patchRegionQuotaDto: PatchRegionQuotaDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('regionQuotasControllerUpdate', 'organizationId', organizationId)
            // verify required parameter 'region' is not null or undefined
            assertParamExists('regionQuotasControllerUpdate', 'region', region)
            // verify required parameter 'patchRegionQuotaDto' is not null or undefined
            assertParamExists('regionQuotasControllerUpdate', 'patchRegionQuotaDto', patchRegionQuotaDto)
            const localVarPath = `/region-quotas/{organizationId}/{region}`
                .replace(`{${"organizationId"}}`, encodeURIComponent(String(organizationId)))
                .replace(`{${"region"}}`, encodeURIComponent(String(region)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchRegionQuotaDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search region-quotas
         * @param {SearchRegionQuotaDto} searchRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasSearchControllerSearch: async (searchRegionQuotaDto: SearchRegionQuotaDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchRegionQuotaDto' is not null or undefined
            assertParamExists('regionQuotasSearchControllerSearch', 'searchRegionQuotaDto', searchRegionQuotaDto)
            const localVarPath = `/region-quotas/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchRegionQuotaDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RegionQuotasApi - functional programming interface
 */
export const RegionQuotasApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RegionQuotasApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Approve a pending request (make it permanent)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotaRequestsControllerApprove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotaRequestsControllerApprove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.quotaRequestsControllerApprove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the current editor\'s remaining daily update budget
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotaRequestsControllerBudget(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotaRequestsControllerBudget(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.quotaRequestsControllerBudget']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Cancel your own pending request and revert the quota
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotaRequestsControllerCancel(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotaRequestsControllerCancel(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.quotaRequestsControllerCancel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the default limits a create request grants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotaRequestsControllerCreateDefaults(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotaRequestsControllerCreateDefaults(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.quotaRequestsControllerCreateDefaults']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List pending quota requests awaiting approval
         * @param {number} [page] Page number (1-indexed)
         * @param {number} [pageSize] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotaRequestsControllerListPending(page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotaRequestsControllerListPending(page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.quotaRequestsControllerListPending']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Reject a pending request and revert the quota
         * @param {string} id 
         * @param {RejectQuotaRequestDto} rejectQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotaRequestsControllerReject(id: string, rejectQuotaRequestDto: RejectQuotaRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotaRequestsControllerReject(id, rejectQuotaRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.quotaRequestsControllerReject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a region quota with the default limits (pending approval)
         * @param {CreateQuotaRequestDto} createQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotaRequestsControllerRequestCreate(createQuotaRequestDto: CreateQuotaRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotaRequestsControllerRequestCreate(createQuotaRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.quotaRequestsControllerRequestCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Request a temporary region quota update (increase)
         * @param {UpdateQuotaRequestDto} updateQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async quotaRequestsControllerRequestUpdate(updateQuotaRequestDto: UpdateQuotaRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.quotaRequestsControllerRequestUpdate(updateQuotaRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.quotaRequestsControllerRequestUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Bulk update region-quotas
         * @param {BulkUpdateRegionQuotaDto} bulkUpdateRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async regionQuotasBulkControllerBulkUpdate(bulkUpdateRegionQuotaDto: BulkUpdateRegionQuotaDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkUpdateResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.regionQuotasBulkControllerBulkUpdate(bulkUpdateRegionQuotaDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.regionQuotasBulkControllerBulkUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a region quota
         * @param {CreateRegionQuotaDto} createRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async regionQuotasControllerCreate(createRegionQuotaDto: CreateRegionQuotaDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.regionQuotasControllerCreate(createRegionQuotaDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.regionQuotasControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List regions a quota can target
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async regionQuotasControllerListRegions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.regionQuotasControllerListRegions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.regionQuotasControllerListRegions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a region quota
         * @param {string} organizationId Organization ID
         * @param {string} region Region ID
         * @param {PatchRegionQuotaDto} patchRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async regionQuotasControllerUpdate(organizationId: string, region: string, patchRegionQuotaDto: PatchRegionQuotaDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.regionQuotasControllerUpdate(organizationId, region, patchRegionQuotaDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.regionQuotasControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search region-quotas
         * @param {SearchRegionQuotaDto} searchRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async regionQuotasSearchControllerSearch(searchRegionQuotaDto: SearchRegionQuotaDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegionQuotaSearchResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.regionQuotasSearchControllerSearch(searchRegionQuotaDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RegionQuotasApi.regionQuotasSearchControllerSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RegionQuotasApi - factory interface
 */
export const RegionQuotasApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RegionQuotasApiFp(configuration)
    return {
        /**
         * 
         * @summary Approve a pending request (make it permanent)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerApprove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotaRequestsControllerApprove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the current editor\'s remaining daily update budget
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerBudget(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotaRequestsControllerBudget(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Cancel your own pending request and revert the quota
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerCancel(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotaRequestsControllerCancel(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the default limits a create request grants
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerCreateDefaults(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotaRequestsControllerCreateDefaults(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List pending quota requests awaiting approval
         * @param {number} [page] Page number (1-indexed)
         * @param {number} [pageSize] Items per page
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerListPending(page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotaRequestsControllerListPending(page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Reject a pending request and revert the quota
         * @param {string} id 
         * @param {RejectQuotaRequestDto} rejectQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerReject(id: string, rejectQuotaRequestDto: RejectQuotaRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotaRequestsControllerReject(id, rejectQuotaRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a region quota with the default limits (pending approval)
         * @param {CreateQuotaRequestDto} createQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerRequestCreate(createQuotaRequestDto: CreateQuotaRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotaRequestsControllerRequestCreate(createQuotaRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Request a temporary region quota update (increase)
         * @param {UpdateQuotaRequestDto} updateQuotaRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        quotaRequestsControllerRequestUpdate(updateQuotaRequestDto: UpdateQuotaRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.quotaRequestsControllerRequestUpdate(updateQuotaRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Bulk update region-quotas
         * @param {BulkUpdateRegionQuotaDto} bulkUpdateRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasBulkControllerBulkUpdate(bulkUpdateRegionQuotaDto: BulkUpdateRegionQuotaDto, options?: RawAxiosRequestConfig): AxiosPromise<BulkUpdateResponseDto> {
            return localVarFp.regionQuotasBulkControllerBulkUpdate(bulkUpdateRegionQuotaDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a region quota
         * @param {CreateRegionQuotaDto} createRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasControllerCreate(createRegionQuotaDto: CreateRegionQuotaDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.regionQuotasControllerCreate(createRegionQuotaDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List regions a quota can target
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasControllerListRegions(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.regionQuotasControllerListRegions(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a region quota
         * @param {string} organizationId Organization ID
         * @param {string} region Region ID
         * @param {PatchRegionQuotaDto} patchRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasControllerUpdate(organizationId: string, region: string, patchRegionQuotaDto: PatchRegionQuotaDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.regionQuotasControllerUpdate(organizationId, region, patchRegionQuotaDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search region-quotas
         * @param {SearchRegionQuotaDto} searchRegionQuotaDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        regionQuotasSearchControllerSearch(searchRegionQuotaDto: SearchRegionQuotaDto, options?: RawAxiosRequestConfig): AxiosPromise<RegionQuotaSearchResponseDto> {
            return localVarFp.regionQuotasSearchControllerSearch(searchRegionQuotaDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RegionQuotasApi - object-oriented interface
 */
export class RegionQuotasApi extends BaseAPI {
    /**
     * 
     * @summary Approve a pending request (make it permanent)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quotaRequestsControllerApprove(id: string, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).quotaRequestsControllerApprove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the current editor\'s remaining daily update budget
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quotaRequestsControllerBudget(options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).quotaRequestsControllerBudget(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Cancel your own pending request and revert the quota
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quotaRequestsControllerCancel(id: string, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).quotaRequestsControllerCancel(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the default limits a create request grants
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quotaRequestsControllerCreateDefaults(options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).quotaRequestsControllerCreateDefaults(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List pending quota requests awaiting approval
     * @param {number} [page] Page number (1-indexed)
     * @param {number} [pageSize] Items per page
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quotaRequestsControllerListPending(page?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).quotaRequestsControllerListPending(page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Reject a pending request and revert the quota
     * @param {string} id 
     * @param {RejectQuotaRequestDto} rejectQuotaRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quotaRequestsControllerReject(id: string, rejectQuotaRequestDto: RejectQuotaRequestDto, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).quotaRequestsControllerReject(id, rejectQuotaRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a region quota with the default limits (pending approval)
     * @param {CreateQuotaRequestDto} createQuotaRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quotaRequestsControllerRequestCreate(createQuotaRequestDto: CreateQuotaRequestDto, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).quotaRequestsControllerRequestCreate(createQuotaRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Request a temporary region quota update (increase)
     * @param {UpdateQuotaRequestDto} updateQuotaRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public quotaRequestsControllerRequestUpdate(updateQuotaRequestDto: UpdateQuotaRequestDto, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).quotaRequestsControllerRequestUpdate(updateQuotaRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Bulk update region-quotas
     * @param {BulkUpdateRegionQuotaDto} bulkUpdateRegionQuotaDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public regionQuotasBulkControllerBulkUpdate(bulkUpdateRegionQuotaDto: BulkUpdateRegionQuotaDto, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).regionQuotasBulkControllerBulkUpdate(bulkUpdateRegionQuotaDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a region quota
     * @param {CreateRegionQuotaDto} createRegionQuotaDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public regionQuotasControllerCreate(createRegionQuotaDto: CreateRegionQuotaDto, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).regionQuotasControllerCreate(createRegionQuotaDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List regions a quota can target
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public regionQuotasControllerListRegions(options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).regionQuotasControllerListRegions(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a region quota
     * @param {string} organizationId Organization ID
     * @param {string} region Region ID
     * @param {PatchRegionQuotaDto} patchRegionQuotaDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public regionQuotasControllerUpdate(organizationId: string, region: string, patchRegionQuotaDto: PatchRegionQuotaDto, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).regionQuotasControllerUpdate(organizationId, region, patchRegionQuotaDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search region-quotas
     * @param {SearchRegionQuotaDto} searchRegionQuotaDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public regionQuotasSearchControllerSearch(searchRegionQuotaDto: SearchRegionQuotaDto, options?: RawAxiosRequestConfig) {
        return RegionQuotasApiFp(this.configuration).regionQuotasSearchControllerSearch(searchRegionQuotaDto, options).then((request) => request(this.axios, this.basePath));
    }
}

