/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { BulkUpdateRegionQuotaDto } from '../models'
// @ts-ignore
import type { BulkUpdateResponseDto } from '../models'
// @ts-ignore
import type { PatchRegionQuotaDto } from '../models'
// @ts-ignore
import type { RegionQuotaSearchResponseDto } from '../models'
// @ts-ignore
import type { SearchRegionQuotaDto } from '../models'
/**
 * RegionQuotasApi - axios parameter creator
 * @export
 */
export const RegionQuotasApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Bulk update region-quotas
     * @param {BulkUpdateRegionQuotaDto} bulkUpdateRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    regionQuotasBulkControllerBulkUpdate: async (
      bulkUpdateRegionQuotaDto: BulkUpdateRegionQuotaDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'bulkUpdateRegionQuotaDto' is not null or undefined
      assertParamExists('regionQuotasBulkControllerBulkUpdate', 'bulkUpdateRegionQuotaDto', bulkUpdateRegionQuotaDto)
      const localVarPath = `/region-quotas/bulk-update`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        bulkUpdateRegionQuotaDto,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Update a region quota
     * @param {string} organizationId Organization ID
     * @param {string} region Region ID
     * @param {PatchRegionQuotaDto} patchRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    regionQuotasControllerUpdate: async (
      organizationId: string,
      region: string,
      patchRegionQuotaDto: PatchRegionQuotaDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'organizationId' is not null or undefined
      assertParamExists('regionQuotasControllerUpdate', 'organizationId', organizationId)
      // verify required parameter 'region' is not null or undefined
      assertParamExists('regionQuotasControllerUpdate', 'region', region)
      // verify required parameter 'patchRegionQuotaDto' is not null or undefined
      assertParamExists('regionQuotasControllerUpdate', 'patchRegionQuotaDto', patchRegionQuotaDto)
      const localVarPath = `/region-quotas/{organizationId}/{region}`
        .replace(`{${'organizationId'}}`, encodeURIComponent(String(organizationId)))
        .replace(`{${'region'}}`, encodeURIComponent(String(region)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(patchRegionQuotaDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Search region-quotas
     * @param {SearchRegionQuotaDto} searchRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    regionQuotasSearchControllerSearch: async (
      searchRegionQuotaDto: SearchRegionQuotaDto,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'searchRegionQuotaDto' is not null or undefined
      assertParamExists('regionQuotasSearchControllerSearch', 'searchRegionQuotaDto', searchRegionQuotaDto)
      const localVarPath = `/region-quotas/search`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(searchRegionQuotaDto, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * RegionQuotasApi - functional programming interface
 * @export
 */
export const RegionQuotasApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = RegionQuotasApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary Bulk update region-quotas
     * @param {BulkUpdateRegionQuotaDto} bulkUpdateRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async regionQuotasBulkControllerBulkUpdate(
      bulkUpdateRegionQuotaDto: BulkUpdateRegionQuotaDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkUpdateResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.regionQuotasBulkControllerBulkUpdate(
        bulkUpdateRegionQuotaDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['RegionQuotasApi.regionQuotasBulkControllerBulkUpdate']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Update a region quota
     * @param {string} organizationId Organization ID
     * @param {string} region Region ID
     * @param {PatchRegionQuotaDto} patchRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async regionQuotasControllerUpdate(
      organizationId: string,
      region: string,
      patchRegionQuotaDto: PatchRegionQuotaDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.regionQuotasControllerUpdate(
        organizationId,
        region,
        patchRegionQuotaDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['RegionQuotasApi.regionQuotasControllerUpdate']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Search region-quotas
     * @param {SearchRegionQuotaDto} searchRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async regionQuotasSearchControllerSearch(
      searchRegionQuotaDto: SearchRegionQuotaDto,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RegionQuotaSearchResponseDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.regionQuotasSearchControllerSearch(
        searchRegionQuotaDto,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['RegionQuotasApi.regionQuotasSearchControllerSearch']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * RegionQuotasApi - factory interface
 * @export
 */
export const RegionQuotasApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = RegionQuotasApiFp(configuration)
  return {
    /**
     *
     * @summary Bulk update region-quotas
     * @param {BulkUpdateRegionQuotaDto} bulkUpdateRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    regionQuotasBulkControllerBulkUpdate(
      bulkUpdateRegionQuotaDto: BulkUpdateRegionQuotaDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<BulkUpdateResponseDto> {
      return localVarFp
        .regionQuotasBulkControllerBulkUpdate(bulkUpdateRegionQuotaDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Update a region quota
     * @param {string} organizationId Organization ID
     * @param {string} region Region ID
     * @param {PatchRegionQuotaDto} patchRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    regionQuotasControllerUpdate(
      organizationId: string,
      region: string,
      patchRegionQuotaDto: PatchRegionQuotaDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .regionQuotasControllerUpdate(organizationId, region, patchRegionQuotaDto, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Search region-quotas
     * @param {SearchRegionQuotaDto} searchRegionQuotaDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    regionQuotasSearchControllerSearch(
      searchRegionQuotaDto: SearchRegionQuotaDto,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<RegionQuotaSearchResponseDto> {
      return localVarFp
        .regionQuotasSearchControllerSearch(searchRegionQuotaDto, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * RegionQuotasApi - object-oriented interface
 * @export
 * @class RegionQuotasApi
 * @extends {BaseAPI}
 */
export class RegionQuotasApi extends BaseAPI {
  /**
   *
   * @summary Bulk update region-quotas
   * @param {BulkUpdateRegionQuotaDto} bulkUpdateRegionQuotaDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegionQuotasApi
   */
  public regionQuotasBulkControllerBulkUpdate(
    bulkUpdateRegionQuotaDto: BulkUpdateRegionQuotaDto,
    options?: RawAxiosRequestConfig,
  ) {
    return RegionQuotasApiFp(this.configuration)
      .regionQuotasBulkControllerBulkUpdate(bulkUpdateRegionQuotaDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Update a region quota
   * @param {string} organizationId Organization ID
   * @param {string} region Region ID
   * @param {PatchRegionQuotaDto} patchRegionQuotaDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegionQuotasApi
   */
  public regionQuotasControllerUpdate(
    organizationId: string,
    region: string,
    patchRegionQuotaDto: PatchRegionQuotaDto,
    options?: RawAxiosRequestConfig,
  ) {
    return RegionQuotasApiFp(this.configuration)
      .regionQuotasControllerUpdate(organizationId, region, patchRegionQuotaDto, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Search region-quotas
   * @param {SearchRegionQuotaDto} searchRegionQuotaDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof RegionQuotasApi
   */
  public regionQuotasSearchControllerSearch(
    searchRegionQuotaDto: SearchRegionQuotaDto,
    options?: RawAxiosRequestConfig,
  ) {
    return RegionQuotasApiFp(this.configuration)
      .regionQuotasSearchControllerSearch(searchRegionQuotaDto, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
