/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BulkInsertResponseDto } from '../models';
// @ts-ignore
import type { BulkInsertRunnerDto } from '../models';
// @ts-ignore
import type { BulkUpdateResponseDto } from '../models';
// @ts-ignore
import type { BulkUpdateRunnerDto } from '../models';
// @ts-ignore
import type { PatchRunnerDto } from '../models';
// @ts-ignore
import type { RunnerSearchResponseDto } from '../models';
// @ts-ignore
import type { SearchRunnerDto } from '../models';
/**
 * RunnersApi - axios parameter creator
 */
export const RunnersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Bulk update runners
         * @param {BulkUpdateRunnerDto} bulkUpdateRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnersBulkControllerBulkUpdate: async (bulkUpdateRunnerDto: BulkUpdateRunnerDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkUpdateRunnerDto' is not null or undefined
            assertParamExists('runnersBulkControllerBulkUpdate', 'bulkUpdateRunnerDto', bulkUpdateRunnerDto)
            const localVarPath = `/runners/bulk-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkUpdateRunnerDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Bulk insert runners
         * @param {BulkInsertRunnerDto} bulkInsertRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnersBulkInsertControllerBulkInsert: async (bulkInsertRunnerDto: BulkInsertRunnerDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkInsertRunnerDto' is not null or undefined
            assertParamExists('runnersBulkInsertControllerBulkInsert', 'bulkInsertRunnerDto', bulkInsertRunnerDto)
            const localVarPath = `/runners/bulk-insert`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkInsertRunnerDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a runner
         * @param {string} id Runner ID
         * @param {PatchRunnerDto} patchRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnersControllerUpdate: async (id: string, patchRunnerDto: PatchRunnerDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('runnersControllerUpdate', 'id', id)
            // verify required parameter 'patchRunnerDto' is not null or undefined
            assertParamExists('runnersControllerUpdate', 'patchRunnerDto', patchRunnerDto)
            const localVarPath = `/runners/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchRunnerDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search runners
         * @param {SearchRunnerDto} searchRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnersSearchControllerSearch: async (searchRunnerDto: SearchRunnerDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchRunnerDto' is not null or undefined
            assertParamExists('runnersSearchControllerSearch', 'searchRunnerDto', searchRunnerDto)
            const localVarPath = `/runners/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchRunnerDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RunnersApi - functional programming interface
 */
export const RunnersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RunnersApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Bulk update runners
         * @param {BulkUpdateRunnerDto} bulkUpdateRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runnersBulkControllerBulkUpdate(bulkUpdateRunnerDto: BulkUpdateRunnerDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkUpdateResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runnersBulkControllerBulkUpdate(bulkUpdateRunnerDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunnersApi.runnersBulkControllerBulkUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Bulk insert runners
         * @param {BulkInsertRunnerDto} bulkInsertRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runnersBulkInsertControllerBulkInsert(bulkInsertRunnerDto: BulkInsertRunnerDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkInsertResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runnersBulkInsertControllerBulkInsert(bulkInsertRunnerDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunnersApi.runnersBulkInsertControllerBulkInsert']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a runner
         * @param {string} id Runner ID
         * @param {PatchRunnerDto} patchRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runnersControllerUpdate(id: string, patchRunnerDto: PatchRunnerDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runnersControllerUpdate(id, patchRunnerDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunnersApi.runnersControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search runners
         * @param {SearchRunnerDto} searchRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async runnersSearchControllerSearch(searchRunnerDto: SearchRunnerDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RunnerSearchResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.runnersSearchControllerSearch(searchRunnerDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RunnersApi.runnersSearchControllerSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RunnersApi - factory interface
 */
export const RunnersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RunnersApiFp(configuration)
    return {
        /**
         * 
         * @summary Bulk update runners
         * @param {BulkUpdateRunnerDto} bulkUpdateRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnersBulkControllerBulkUpdate(bulkUpdateRunnerDto: BulkUpdateRunnerDto, options?: RawAxiosRequestConfig): AxiosPromise<BulkUpdateResponseDto> {
            return localVarFp.runnersBulkControllerBulkUpdate(bulkUpdateRunnerDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Bulk insert runners
         * @param {BulkInsertRunnerDto} bulkInsertRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnersBulkInsertControllerBulkInsert(bulkInsertRunnerDto: BulkInsertRunnerDto, options?: RawAxiosRequestConfig): AxiosPromise<BulkInsertResponseDto> {
            return localVarFp.runnersBulkInsertControllerBulkInsert(bulkInsertRunnerDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a runner
         * @param {string} id Runner ID
         * @param {PatchRunnerDto} patchRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnersControllerUpdate(id: string, patchRunnerDto: PatchRunnerDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.runnersControllerUpdate(id, patchRunnerDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search runners
         * @param {SearchRunnerDto} searchRunnerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        runnersSearchControllerSearch(searchRunnerDto: SearchRunnerDto, options?: RawAxiosRequestConfig): AxiosPromise<RunnerSearchResponseDto> {
            return localVarFp.runnersSearchControllerSearch(searchRunnerDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RunnersApi - object-oriented interface
 */
export class RunnersApi extends BaseAPI {
    /**
     * 
     * @summary Bulk update runners
     * @param {BulkUpdateRunnerDto} bulkUpdateRunnerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runnersBulkControllerBulkUpdate(bulkUpdateRunnerDto: BulkUpdateRunnerDto, options?: RawAxiosRequestConfig) {
        return RunnersApiFp(this.configuration).runnersBulkControllerBulkUpdate(bulkUpdateRunnerDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Bulk insert runners
     * @param {BulkInsertRunnerDto} bulkInsertRunnerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runnersBulkInsertControllerBulkInsert(bulkInsertRunnerDto: BulkInsertRunnerDto, options?: RawAxiosRequestConfig) {
        return RunnersApiFp(this.configuration).runnersBulkInsertControllerBulkInsert(bulkInsertRunnerDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a runner
     * @param {string} id Runner ID
     * @param {PatchRunnerDto} patchRunnerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runnersControllerUpdate(id: string, patchRunnerDto: PatchRunnerDto, options?: RawAxiosRequestConfig) {
        return RunnersApiFp(this.configuration).runnersControllerUpdate(id, patchRunnerDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search runners
     * @param {SearchRunnerDto} searchRunnerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public runnersSearchControllerSearch(searchRunnerDto: SearchRunnerDto, options?: RawAxiosRequestConfig) {
        return RunnersApiFp(this.configuration).runnersSearchControllerSearch(searchRunnerDto, options).then((request) => request(this.axios, this.basePath));
    }
}

