/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Backoffice API
 * Internal API for Daytona backoffice operations - search, bulk updates, and admin tasks
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@daytona.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BulkUpdateResponseDto } from '../models';
// @ts-ignore
import type { BulkUpdateSandboxDto } from '../models';
// @ts-ignore
import type { PatchSandboxDto } from '../models';
// @ts-ignore
import type { SandboxSearchResponseDto } from '../models';
// @ts-ignore
import type { SearchSandboxDto } from '../models';
/**
 * SandboxesApi - axios parameter creator
 */
export const SandboxesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Bulk update sandboxes
         * @param {BulkUpdateSandboxDto} bulkUpdateSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sandboxesBulkControllerBulkUpdate: async (bulkUpdateSandboxDto: BulkUpdateSandboxDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'bulkUpdateSandboxDto' is not null or undefined
            assertParamExists('sandboxesBulkControllerBulkUpdate', 'bulkUpdateSandboxDto', bulkUpdateSandboxDto)
            const localVarPath = `/sandboxes/bulk-update`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkUpdateSandboxDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a sandbox
         * @param {string} id Sandbox ID
         * @param {PatchSandboxDto} patchSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sandboxesControllerUpdate: async (id: string, patchSandboxDto: PatchSandboxDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sandboxesControllerUpdate', 'id', id)
            // verify required parameter 'patchSandboxDto' is not null or undefined
            assertParamExists('sandboxesControllerUpdate', 'patchSandboxDto', patchSandboxDto)
            const localVarPath = `/sandboxes/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchSandboxDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search sandboxes
         * @param {SearchSandboxDto} searchSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sandboxesSearchControllerSearch: async (searchSandboxDto: SearchSandboxDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'searchSandboxDto' is not null or undefined
            assertParamExists('sandboxesSearchControllerSearch', 'searchSandboxDto', searchSandboxDto)
            const localVarPath = `/sandboxes/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(searchSandboxDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SandboxesApi - functional programming interface
 */
export const SandboxesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SandboxesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Bulk update sandboxes
         * @param {BulkUpdateSandboxDto} bulkUpdateSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sandboxesBulkControllerBulkUpdate(bulkUpdateSandboxDto: BulkUpdateSandboxDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BulkUpdateResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sandboxesBulkControllerBulkUpdate(bulkUpdateSandboxDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.sandboxesBulkControllerBulkUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a sandbox
         * @param {string} id Sandbox ID
         * @param {PatchSandboxDto} patchSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sandboxesControllerUpdate(id: string, patchSandboxDto: PatchSandboxDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sandboxesControllerUpdate(id, patchSandboxDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.sandboxesControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search sandboxes
         * @param {SearchSandboxDto} searchSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sandboxesSearchControllerSearch(searchSandboxDto: SearchSandboxDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SandboxSearchResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sandboxesSearchControllerSearch(searchSandboxDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SandboxesApi.sandboxesSearchControllerSearch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SandboxesApi - factory interface
 */
export const SandboxesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SandboxesApiFp(configuration)
    return {
        /**
         * 
         * @summary Bulk update sandboxes
         * @param {BulkUpdateSandboxDto} bulkUpdateSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sandboxesBulkControllerBulkUpdate(bulkUpdateSandboxDto: BulkUpdateSandboxDto, options?: RawAxiosRequestConfig): AxiosPromise<BulkUpdateResponseDto> {
            return localVarFp.sandboxesBulkControllerBulkUpdate(bulkUpdateSandboxDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a sandbox
         * @param {string} id Sandbox ID
         * @param {PatchSandboxDto} patchSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sandboxesControllerUpdate(id: string, patchSandboxDto: PatchSandboxDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.sandboxesControllerUpdate(id, patchSandboxDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search sandboxes
         * @param {SearchSandboxDto} searchSandboxDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sandboxesSearchControllerSearch(searchSandboxDto: SearchSandboxDto, options?: RawAxiosRequestConfig): AxiosPromise<SandboxSearchResponseDto> {
            return localVarFp.sandboxesSearchControllerSearch(searchSandboxDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SandboxesApi - object-oriented interface
 */
export class SandboxesApi extends BaseAPI {
    /**
     * 
     * @summary Bulk update sandboxes
     * @param {BulkUpdateSandboxDto} bulkUpdateSandboxDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sandboxesBulkControllerBulkUpdate(bulkUpdateSandboxDto: BulkUpdateSandboxDto, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).sandboxesBulkControllerBulkUpdate(bulkUpdateSandboxDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a sandbox
     * @param {string} id Sandbox ID
     * @param {PatchSandboxDto} patchSandboxDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sandboxesControllerUpdate(id: string, patchSandboxDto: PatchSandboxDto, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).sandboxesControllerUpdate(id, patchSandboxDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search sandboxes
     * @param {SearchSandboxDto} searchSandboxDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sandboxesSearchControllerSearch(searchSandboxDto: SearchSandboxDto, options?: RawAxiosRequestConfig) {
        return SandboxesApiFp(this.configuration).sandboxesSearchControllerSearch(searchSandboxDto, options).then((request) => request(this.axios, this.basePath));
    }
}

