/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Billing API
 * Daytona Billing API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */




export const BalanceType = {
    BalanceTypeCommit: 'commit',
    BalanceTypeCredit: 'credit',
} as const;

export type BalanceType = typeof BalanceType[keyof typeof BalanceType];



