/* tslint:disable */
/* eslint-disable */
/**
 * Daytona Billing API
 * Daytona Billing API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BalanceApplicableTo } from './balance-applicable-to';
// May contain unused imports in some cases
// @ts-ignore
import type { BalanceType } from './balance-type';

export interface Balance {
    'applicableTo'?: BalanceApplicableTo;
    /**
     * BalanceCents is the amount in cents currently available to draw down.
     */
    'balanceCents'?: number;
    'createdAt'?: string;
    /**
     * ExpiresAt is when access to the balance ends. Unset for balances that never expire.
     */
    'expiresAt'?: string;
    /**
     * GrantedAmountCents is the total amount in cents originally granted.
     */
    'grantedAmountCents'?: number;
    'id'?: string;
    'name'?: string;
    'type'?: BalanceType;
}



